### ISSUE TITLE
[FAQ]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#10]
- [x] Criar página (page) Perguntas Frequentes 

- [x] Investigação: se será um CPT FAQ ou Bloco
  - Utilizar bloco gutenberg para o acordeão e utilizar plugin que estende o gutenberg (pesquisar)
  - Utilizar bloco de âncora

https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=209-47&mode=design&t=9HTLgS8rkCbFwQTd-0

**Comment by thiagolamonte** [comment]
validação:

https://dev.midianinja.org/perguntas-frequentes/

**Comment by daphnemartinsba** [comment]
**Desktop**
- [ ] 1366: adequar à resolução, anúncio ocupa a extensão horizontal da tela inteira
- [ ] 1920 e 1366: Centralizar banners de perguntas frequentes
- [ ] 1920: aumentar tamanho dos banners 
- [ ] 1920 e 1366: Deixar ícone do mouse com aparência clicável ao passar mouse em cima dos elementos da sanfona
- [ ] 1920 e 1366: Adequar alinhamento do conteúdo textual do parágrafo abaixo do título do banner perguntas frequentes
- [ ] 1920 e 1366: Texto abaixo de pergunte aos ninjas: deixar o email como bold e a palavra contato (última palavra do parágrafo) e adequar alinhamento do texto (quebra de linha após o email de contato)
- [ ] 1920 e 1366: Título O que é o mídia ninja alterar cor da fonte para #111111
- [ ] 1920 e 1366: aumentar distância entre títulos e parágrafos da sanfona
- [ ] 1920 e 1366: alterar background da newsletter e adequar alinhamento do conteúdo do texto conforme figma
- [ ] Botão "ir para área de contato" direcionar para fale conosco
- [ ] 1920 e 1366: diminuir área embaçada no banner de perguntas frequentes  

**Mobile** 
Validação em andamento

**Comment by thiagolamonte** [comment]
não consegui reproduzir as situações de 1920e 1366, nesses ajustes observei os elementos em larguras a cima de 1366.

**Comment by caio-ascava** [comment]
- [ ] No Figma a Lupa está no mesmo sentido (espaçamento) da borda do quadro de Pergunte aos Ninjas, mas na resolução 1366x768 há ainda um espaço a ser reduzido.
- [ ] line height ajustar para 38.4px nos títulos e dentro de cada quadro para 28.8px em "O que é Mídia Ninja" e 30px em "Como Funciona?"
- [ ] 1366: aumentar distância entre títulos e parágrafos da sanfona
- [ ] aumentar tamanho dos banners

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1c2f8f88-9852-48e0-81cf-df9987a581a2)

- [ ] As linhas que separam os assuntos precisar ser ajustadas quanto a cor ou espessura.
- [ ] Ajustar fonte das letras do retangulo preto: QUEM FINCANCIA A MIDIA NINJA É VOCÊ!
- [ ] Ajustar a borda do retânulo preto "redondas"

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/603bb953-5646-4c25-a9d2-d2f64d9c7ec9)

- [ ] Adequar a fonte de NewsLetter conforme Figma.
- [ ] Os ícones das redes sociais não estão aparecendo nem no cabeçalho e nem no rodapé

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/4375c978-dc69-4f40-9327-f9b17e89c05e)

No iphone 15 Pro max
- [ ] Retirar a seta antes das opções
- [ ] Ajustar cor/espessura das linhas 
- [ ] Em Quais os Planos, o P deve ser maiúsculo!
- [ ] Os títulos "O que é o Midia Ninja", "Como funciona (sem a interrogação)" e "Quais os Planos (com P maiúsculo)"

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/d379d352-cead-4775-97fc-67b42728531b)

**Comment by caio-ascava** [comment]
- [ ] O banner perguntas frequentes no figma está maior as letras. Diminuir o tamanho do banner para que fique igual ao do figma
- [ ] o banner de pergunte aos ninjas, no figma apresenta a caixa de texto maior, dentro do quadro.
- [ ] Precisa ajustar a opacidade pois no Figma apresenta-se levemente mais transparente.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/8f3162ed-2683-4aab-96bf-a35fd89b0cbf)

**Comment by thiagolamonte** [comment]
validação: 

https://dev.midianinja.org/perguntas-frequentes/

comentários: 

O contepudo do site tem 1170px de largura e a a lupa do header está deslocada para direita extrapolando a largura do conteúdo. Por isso que fica desalinhado. 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/3bf395cc-d1a8-41f7-a828-54cf7d2b14a4)

A imagem acima é da página de edição que monta o conteúdo das sanfonas. Os títulos da sidebar (em cinza), são exatamente os títulos do Conteúdo que antecedem as sanfonas (Ao colocar um título na página ele já vai automaticamnte para os dois lugares ) . Então é necessário definir um padrão de exibição, com ou sem "?" com ou sem palavras em maiusculo e minusculo. 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/40b3f2ca-ec71-4657-9d9e-1733d7fd0018)

Sobre as setas no iphone 15 pro. Elas de fato aparecem nesse modelo de celular, não cheguei a uma solução pois elas são o mesmo elemento de abrir e fechar a sanfona. Se tiro elas o sinal de mais e menos do lado oposto some também

**Comment by daphnemartinsba** [comment]
Retorno  em #82
