### ISSUE TITLE
[ACESSIBILIDADE] Vlibras e plugins de contraste e áudio

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#102]
- [x] Instalar e configurar o VLibras 
- [x] Pesquisar plugin alternativo ao audima
  - testar e retornar aqui na issue e no canal
- [x] Pesquisar plugin para alto contraste
  - testar e retornar aqui na issue e no canal

**Comment by julialaurentino** [comment]
Plugins recomendados para substituir o Audima:

- Text To Speech TTS Accessibility https://wordpress.org/plugins/text-to-audio/ 
- GSpeech https://wordpress.org/plugins/gspeech/ 
 
Plugin para contraste:
- WP Acessibility https://br.wordpress.org/plugins/wp-accessibility/

**Comment by julialaurentino** [comment]
implementado em dev para validação

**Comment by caio-ascava** [comment]
Validação de contraste e tamanho de fonte ok, no entanto: 

- [ ] Avaliar erro ao abrir o Vlibras

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e4f27669-3cd9-4bce-81a4-fc78d1ae82fd)

**Comment by daphnemartinsba** [comment]
- [ ] audima não está aplicando para single de opiniões

**Comment by julialaurentino** [comment]
> * [ ]  audima não está aplicando para single de opiniões

o plugin usado foi o  Text To Speech TTS Accessibility https://wordpress.org/plugins/text-to-audio/, como reportado, ele na versão gratuita só funciona para um tipo de post (pode ser determinado qual). Para usar em mais tipos de posts, é preciso contratar o PRO (repassado os dados para @estercmandrade e @marinarcruz )

**Comment by estercmandrade** [comment]
Vamos avaliar e testar o plugin GSpeech do google em DEV para eventualmente alterar o plugin.
Acompanhamento na issue #152
