### ISSUE TITLE
[SINGLE NOTÍCIAS] Ajustes gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#105]
- [x] conteúdo de texto está destalinhado com o elemento 'por' dos autores:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/14a6ce25-0727-4507-a2bb-d566fe47f843)

- Confirmar: anúncio precisa ser estilizado
- [x] tag de categorias precisa ser puxada com a mesma formatação da home, com o texto em caixa alta 
- [x] solicitação de alteração do cliente: Alterar ordem de redes sociais do autor e do footer: WhatsApp - Facebook - Twitter - Telegram 
- [x] Exibir legenda das imagens, no corpo do texto e na imagem destacada
- [x] Inserir link no componente do co authors: direcionar para o afluente
- [x] além de puxar a cor tag (etiqueta) de categorias (editorias) da imagem de destaque deve ser em caixa alta, como a da home 
- [x] galeria perde alinhamento na formatação quando insere legenda em uma das fotos
- [x] solicitação de alteração do cliente: estilo da fonte: retirar espaço entre letras, deixar 0. Manter cor prevista no figma
- [x] Inserir leia também em postagens sem componente de co authors:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/c55affd0-f47a-48a3-8e99-3d9527a936db)

- [x] Redes sociais no footer estão desalinhadas em postagens sem co authors 
- [x] alinhar blocos de vídeo ao tamanho do texto
- [x] Fonte de título da single: h1, 48 px, 800 weight, line height: e -3% de letter spacing  

- foi atualizada a largura do menu no dev

**Comment by barbaburns** [comment]
Sobre posts relacionados ( leia mais ) não parece ter a ver com a presença de co-autors e sim sobre não ter categoria relacionada.

**Comment by daphnemartinsba** [comment]
> Sobre posts relacionados ( leia mais ) não parece ter a ver com a presença de co-autors e sim sobre não ter categoria relacionada.

@everaldomatias está solucionando enquanto atua na issue #110

**Comment by daphnemartinsba** [comment]
- [ ] quebrar linha das legendas das imagens de destaque para que não quebre o layout
exemplo de legenda muito grande: https://midia.ninja/organizacoes-de-mulheres-estimulam-diversificacao-de-cultivos/

**Comment by filipesouzadev** [comment]
@daphnemartinsba conforme falamos na chamada, o bruno solicitou a retirada do ícone de compartilhamento (copiar link) da seção de compartilhamento. também nao teremos o o ícone do instagram, pois nao temos ainda soluçao para compartilhamento via instagram.

**Comment by filipesouzadev** [comment]
@daphnemartinsba conforme falamos na chamada eu nao consigo alterar o html do tiktok para que se adeque ao nosso conteúdo.

**Comment by caio-ascava** [comment]
As correções pendentes serão tratadas na issue #146 [SINGLE NOTÍCIAS] Correções pontuais
[#146](https://github.com/midianinja/ninja-wp-theme/issues/146)
