### ISSUE TITLE
[SINGLE DE NOTÍCIAS] Exibir sempre o CARD do afluente mãe.

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#106]
- [ ] Quando notícias estiver com o marcador do Afluente, exibir sempre o CARD do afluente mãe.

Exemplo: https://midia.ninja/conheca-eloise-matos-primeira-mulher-a-ser-a-voz-da-apuracao-do-carnaval-de-sao-paulo/
Essa notícia está com os marcadores do afluente Planeta Ella e Perfil d'Ella, deve aparecer o CARD do Planeta Ella.

**Comment by daphnemartinsba** [comment]
resolvida na issue #91
