### ISSUE TITLE
[RESULTADOS DE BUSCA] Ajustes gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#109]
- [x] ao clicar na lupa ocorre o direcionamento para a página de busca vazia, por isso, ao selecionar os filtros permanece constando como 0 resultados encontrados, deve listar todas as postagens
- [x] utilizar modelo dos dropdowns nos componentes: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=2667-5961&mode=design&t=N4gSHWoL8vZgYKNe-0 
- [x] traduzir strings pelo wpml, seguir orientações: https://docs.hacklab.com.br/docs/wpml-internacionalizacao/
- [x] textos grandes ficam atrás da lupa:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/5c1d5760-458c-4133-854f-f6410b40d511)

- [x] ao clicar em new search ele mantém a pesquisa antiga no campo de busca
- [x] botão back to home não direciona para a home
- [x] filtro filter by all não lista todas. Teste: pesquisei por a, filtrei por opinião e ai filtrei por todas, nada aconteceu, o mesmo ocorre quando filtra por notícias e depois por todas
- [x] filtrar pelos mais antigos não lista as postagens na mesma ordem que o painel, com news filtrado, o mesmo ocorre com opiniões 
- pesquisei por a e selecionei o filtro, fui para o painel e fiz a mesma coisa mas ao invés de selecionar o filtro visitei a última página
- ao filtrar por all, não mistura as opiniões com notícias priorizando a ordenação pela data
- [x] alterar background para #f5f5f5

- [x] Mobile Samsung: tag fica cortada um pouco para fora da thumb:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/55b0f547-3199-4bf5-889f-679db92183d8)

- [x] Mobile Samsung: adequar paginação ao alinhamento do figma
- [x] Mobile Samsung: diminuir espaçamento entre filtros e adequá-los ao estilo do figma

**Comment by daphnemartinsba** [comment]
- [ ] Alguns avatares listados não são dos autores (colunistas)
    - em alguns casos a imagem do avatar está no conteúdo do texto: Skol: Novo posicionamento ou surf na nossa onda?
    - em outros casos o texto não tem imagem e mesmo assim a imagem não é a do colunista: https://midia.ninja/opiniao/o-golpe-do-satelite-e-a-outra-face-da-lista-do-fachin/

- [ ] Na lista de busca, o nome do autor da opinião não deve ficar separado do título e avatar:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/cbbebcca-f2a1-4fc3-8681-28a58a73b324)

- [ ] Quando o resultado só tem uma opinião, não deve ficar grudada no rodapé
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/3bd53a7e-0e53-433a-907a-01ff41702d7f)


* Não é prioritária:
- [ ] listar notícias por ordem de leitura, da esquerda para a direita de cima para baixo

**Comment by daphnemartinsba** [comment]
- Modelo de dropdown não será ajustado nessa issue

**Comment by daphnemartinsba** [comment]
Devido aos ajustes realizados durante as duas últimas semanas, o ajuste do dropdown deve ser retomado

**Comment by thiagolamonte** [comment]
foi feita uma proposta de estilo para o dropdown que precisa de pequenos ajustes

o checkbox sobre a ordenação dos posts da esquerda para direita de cima pra baixo foi pedido pra ser desconsiderado por hora.
