### ISSUE TITLE
[MIGRAÇÃO] Segundo pacote de migração: post-from-post_type-to-post_type

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#11]
- [x] Migrar posts do CPT News para CPT Posts

![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/49c4238b-8900-4d70-a431-48bb1b008836)

**Comment by estercmandrade** [comment]
![Captura de tela 2024-01-18 141930](https://github.com/midianinja/ninja-wp-theme/assets/91154843/c05c2cac-c8ee-4590-80f4-fe2043c4aad3)

**Comment by guimaricardo** [comment]
migrados todos os pots em CPT news, com category noticias, para CPT post. Ficaram 1080 posts no cpt news com category's diversas.
