### ISSUE TITLE
[HOME] Aplicar estilo na edição

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#111]
Deixar a visualização da edição mais amigável, próxima à visualização da home
- [x] inserir títulos dos blocos últimos posts no painel de edição:
Os blocos especiais e mais lidas:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/3aa6f6a7-fa28-42ed-9881-a0fc329586f8)

- [x] deixar blocos mais parecidos com a visualização na home

**Comment by thiagolamonte** [comment]
validação: 

Entrar na home de DEV e ir em editar a página
