### ISSUE TITLE
[EDITORIAS] Cores das categorias, subcategorias e etiquetas

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#112]
- [ ] revisar/ajustar: as tags (estiquetas) devem ser padronizadas, e possuir as cores das editorias (utilizar tag do bloco de editoria da home como base)

Páginas com tags:
- [x]  home
- [x] notícias
- [x]  archive notícias
- [ ] archives editorias
- [x] página de busca
- [ ] especiais

- [ ] Archives editorias: ter tag (etiqueta) para cada editoria marcada na postagem

 

- [x] As cores das editorias devem ser aplicada para suas subscategorias:
verde - agricultura
3A8B51

 verde - meio ambiente
99CE56

 verde - esportes
7AE695

 ciano - política
76C7E6

 azul - especiais
3F24E5

 azul - audiovisual
277EA3

 roxo - feminismos
8C52FF

 roxo - educação
C9ADFF

 rosa - lgbtqiap+
E14FCE

 rosa - tecnologia
F0A8E7

 laranja - indígenas
F27900

 laranja 2 - negritudes
F1BC4E

 vermelho 1 - institucional
F63333

 vermelho 2 - cultura
DB565E

 amarelo - alimentação
F7F100

salmão - economia
F6B2B2

violeta - saúde
BB6BD9

vermelho - internacional
F63333 (texto FFFFFF)

**Comment by daphnemartinsba** [comment]
Direitos Humanos: C6C93E -verde amarelo

**Comment by caio-ascava** [comment]
- [ ] Algumas thumbs não estão trazendo a categoria;
- [ ] Layout quebra quando não traz a tag de categoria.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/05d4a79e-a7e8-4466-9926-45f74d07e210)

**Comment by daphnemartinsba** [comment]
- Layout quebra quando não traz a etiqueta de categoria: será resolvida na issue #158

Ajustes finos mapeados:
As etiquetas não foram aplicadas para  archives editorias e especiais
