### ISSUE TITLE
[FALE CONOSCO] termo de uso, redes sociais, texto e imagem

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#114]
- [x] Inserir termo de uso
- [x] inserir e alterar ordem das redes sociais: Instagram - X - Facebook - Youtube - Tik Tok 
- [x] alterar foto do banner para ficar igual à utilizada no desktop
- [x]  aumentar espaço entre os textos: entre "contato" e "fale conosco"; e entre "fale conosco" e o o texto de apoio que vem logo abaixo: no figma tá: 16px entre "contato" e "fale conosco", e 21px entre "fale conosco" e o bloco de texto de apoio
- o espaço entre linhas de um grupo (fale conosco) sempre precisa ser menor que o espaço entre os grupos.

**Comment by thiagolamonte** [comment]
não foi colocado o aceite de termos pois não existe ainda as páginas de termos de uso e de politicas de privacidade

**Comment by daphnemartinsba** [comment]
- [ x ] Links de twitter e facebook não redirecionam para as redes sociais porque a url contém o endereço de fale conosco antes da url da rede social

- [ ] Quando não preenche os campos, os avisos de preenchimento quebram a formatação, o blur não vai até o fim do bloco e perde o alinhamento com o bloco A Mídia NINJA:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/8a8c6698-782b-439d-ab0c-057a53d0de33)


- [ ] Mobile Samsung e Iphone: texto: "A Mídia ninja" para "A Mídia NINJA" (sem as aspas)
- [ ] Mobile Samsung e Iphone: diminuir largura do texto e do separador, para deixar conforme figma
  figma:
  
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/7d4b3cd9-16bb-46e9-a1f2-8d6a2afab788)

staging:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/bc98a110-f691-4f47-aaed-b482e68ac451)

- [ ] Mobile Samsung S23: Alterar cor do bloco
- [ ] Mobile Samsung S23 e Iphone: Inserir as redes sociais nas mesma ordem do desktop 

- O espaço entre Fale e Conosco está menor que os espaços entre o título acima e o parágrafo abaixo. À confirmar se o implementado contempla visto que a distância repassada em pixels não correspondeu à disponível no protótipo do figma
Distância entre contato e fale conosco: 32
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/83b3573f-7f01-45cc-86f2-97d9f366c252)

Distância entre fale e conosco: 29 
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/98b29af2-4b3b-4390-964c-6f8d8bf24899)

Distância entre fale conosco e parágrafo: 43
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/94abafe8-c6ce-421d-9ece-9bb35cd02af6)

dev:

- [ ] Distância entre contato e fale conosco: 34 px
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/777458c7-6926-4dca-87e4-e2002eb91e66)



- Distância entre fale e conosco: 29 
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/0afea3ff-a4bc-4a35-8975-18d408bb4454)

- Distância entre fale conosco e parágrafo: 43px
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/17cc9589-dbfd-4d2d-b2f5-f202a3afd3d9)

**Comment by caio-ascava** [comment]
Aguardando conclusão das ações mapeadas anteriormente.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/af980135-c15c-4173-961e-ab7c261491e4)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/3502e69a-8ba6-4f66-bb60-bb8cca9f7fa5)

**Comment by caio-ascava** [comment]
Essa issue foi concluída e aberta outra para tratar os ícones de redes sociais via mobile, atualmente em prod aparece apenas a de Instagram

[FALE CONOSCO] Redes sociais MOBILE
[#155](https://github.com/midianinja/ninja-wp-theme/issues/155)
