### ISSUE TITLE
[SINGLE FOTOGRAFIAS] Ajustes gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#115]
- [x] Investigar: a imagem de destaque não está na proporção correta, tá menor

- [ ] Exibir resumo do post: usar H3 da guideline

- [x] padronizar tamanho das thumbs de acesse mais galerias, conforme figma:
 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e62b862b-627c-4ec8-9c04-dfe8109a8214)

- revisão em andamento

**Comment by thiagolamonte** [comment]
Rever h3 nos tokens

**Comment by caio-ascava** [comment]
- [ ] Rever no design tokens: H3

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b63c68d9-bccb-465f-ac2e-0f40b2fd18b7)

**Comment by daphnemartinsba** [comment]
> * [ ]  Rever no design tokens: H3
> 
> ![Image](https://private-user-images.githubusercontent.com/151761173/326564444-b63c68d9-bccb-465f-ac2e-0f40b2fd18b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQ1NTksIm5iZiI6MTcxNDQ4NDI1OSwicGF0aCI6Ii8xNTE3NjExNzMvMzI2NTY0NDQ0LWI2M2M2OGQ5LWJjY2ItNDY1Zi1hYzJlLTBmNDBiMmZkMThiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzM3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjdiYWFjMzMwZTNmNDk0NGZhNGJlYzliNGU2ZjQyMTI0YjZjOWFlMDkyODgwYmU0ZjhlZThiNTdmYzQ5YWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahVNt2iQw32cGfizZt9fiyzqdhTskVuHwBzpt-sXaXI)

Issue #88
