### ISSUE TITLE
[RESULTADO DE BUSCA VAZIA] tradução de string

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#117]
- [ ]  Traduzir a string pelo WPML

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ed87796a-dd05-4345-b02c-fad3eed4b82d)

**Comment by daphnemartinsba** [comment]
traduzida:




![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/c63b022b-f0f1-4fb8-bfa8-8ee1b58ebaa5)
