### ISSUE TITLE
[ARCHIVE AFLUENTES] Ajustes finos

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#118]
- [x] ícone de lupa deve realizar a busca ao ser clicado
- [x] dar de 2 ou 3 px para a barra de digitação, quando clica em cima do campo de busca
- [x] Investigar e dar retorno do motivo na issue: ao pesquisar somente por cine, exibe demais afluentes, o mesmo não ocorre quando pesquisa por design, por exemplo

**Comment by dioliviers** [comment]
Sobre o buscar já é um comportamento normal

**Comment by daphnemartinsba** [comment]
- [ ] Mobile Iphone pro max 14 e samsung s23: Arredondar borda do Banner 
- [ ] Mobile Iphone pro max 14 e samsung s23: Ajustar tamanho do banner e do blur, conforme figma, no dev está muito grande
- [ ] Mobile Iphone pro max 14: ajustar ícone do campo de busca:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/613d2482-0a2d-45a3-ba9a-122a5cae04c0)

**Comment by dioliviers** [comment]
Ajustado o tamanho do blur, background, lupa e efetuado alguns ajustes de distanciamento.

Sobre o grid ele está com o comportamento normal, a div content, define que o body esteja dentro do grid, já aproveitei e tirei o padding padrão do grid.

OBS: o banner ele está com o width:auto, essa funcionalidade, faz com que o banner fique com a largura automática, ao meu ver não compensa definir tamanhos absolutos em diferentes resoluções. Ou seja o banner está flexivel, é um comportamento normal.

**Comment by caio-ascava** [comment]
Não foi identificado o retorno quanto ao checkbox:
- [ ] Investigar e dar retorno do motivo na issue: ao pesquisar somente por cine, exibe demais afluentes, o mesmo não ocorre quando pesquisa por design, por exemplo.
Avaliação complementar: 
Ao inserir o termo "cine" ele trouxe os afluentes "Cine Ninja", "Design Ativista", "Estudantes NINJA" e "Minas NINJA"
Ao inserir o termo "design" ele trouxe os afluentes "Casa Ninja Amazônia" e "Design Ativista"
Ao inserir o termo "NINJA", ele trouxe todos os 12 afluentes
Ao inserir o termo "ativ" ele trouxe 11 afluentes, exceto "S.O.M."
Ao inserir o termo "ativista" ele trouxe 5 afluentes "Cine Ninja", "Design Ativista", "FODA", "Poderes Pretos" e "Xepa Ativismo".
