### ISSUE TITLE
[COMPARTILHAMENTO] Configurar imagens das thumbs nos links compartilhados

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#119]

**Comment by daphnemartinsba** [comment]
- [ ] imagem não carrega ao postar no twitter: 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/8ec03010-13e7-4330-a4b7-272ee39fc71a)

- [ ] Alterar imagem de compartilhamento da página inicial, no momento é o balão de opinião em branco
Imagem do telegram:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e1a4cea6-1445-48f0-936a-c5a40177e436)

**Comment by Thayna-Zacharias** [comment]
![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/05742ebe-668f-432f-addf-a10f2316628f)

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/1fe21c85-832b-4b88-9a28-b37589b493c0)

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/d436f061-75a9-4db5-abed-7f304bb986cc)

 A página da home estava sem imagem destacada, foi adicionada uma imagem e já aparece no compartilhamento.

**Comment by caio-ascava** [comment]
Validação realizada em todas as plataformas disponíveis para compartilhamentos.

Exemplos:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/09126c41-a210-4473-bde4-77dc9f8d3b90)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/5308ac28-d87f-4b34-88cd-d41da0aeee97)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0f2ddad6-878f-4152-8099-802ed38d8b39)
