### ISSUE TITLE
[ARCHIVE NOTÍCIAS] GENÉRICA: ajustes no grid, paginação e slide

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#120]
Tarefa prioritária:
- [x] Quantidade de posts do grid deve ser 8
- [x] alguns números da paginação não direcionam ao serem clicados

Ajustes finos:
- [ ] alterar ordem da coloração da bolinha do slide de mais lidas

Mobile (Samsung S23 e Iphone Pro Max 14):
- [ ] deixar thumb do banner principal igual ao da home
- [x] Samsung S23: thumbs à direita do banner: estão coladas no canto da tela:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a6535a50-02b1-4ca1-b461-f3484f8305da)

- [x] thumbs à direita do banner: deixar igual à home, somente duas
- [x] Bloco mais lidas está no fim da página
- [x] Samsung S23: tem um bloco que não está carregando:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/2977f414-340c-44ec-b43d-6ad7f4433226)

- [x] diminuir distância entre notícias do grid
- [x] algumas thubms estão sem bordas redondas:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/9cdbed97-6670-47a1-82fa-9588a981905a)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/b2153268-5870-4842-a944-164603f9779b)

**Comment by caio-ascava** [comment]
- [ ] A partir da pagina 12, foi identificado que as noticias que não possuem classificação de categoria (tag) quebram layout.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0423916a-2c42-4c96-9a4f-387e23ce6a73)

**Comment by daphnemartinsba** [comment]
Comportamento do layout da thumb será realizado na #158
