### ISSUE TITLE
[SINGLE OPINIÃO] Avatar e componente do co authors

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#122]
*** Repassado pelo cliente**

- [x] Não aparece componente de co authors 
  - da colunista renata souza
     - não está como colunista
   - outro exemplo: Nilma lino
        - Está marcado como colunista
  
- [x] avatar não está aparecendo

**Comment by daphnemartinsba** [comment]
No processo de QA foi feito um levantamento breve (infelizmente pelo número de postagens não é possível varrer todas) de algumas opiniões que estão com avatar sem foto

Tem um caso específico que exemplifica o comportamento. Em algumas postagenso colunista ninja é puxado de Autores Convidados, em outros casos da a impressão de que é puxado de Usuários:
Colunista NINJA sem foto: https://midia.ninja/opiniao/as-ondas-de-calor-e-a-saude-nas-cidades-da-amazonia/
Colunista NINJA com foto/marcação de colunista: https://midia.ninja/opiniao/orcamento-para-o-meio-ambiente-entre-o-discurso-e-a-realidade/

Demais exemplos encontrados:
https://midia.ninja/opiniao/qual-a-relacao-entre-a-expressao-de-genero-e-a-violencia-no-carnaval/
https://midia.ninja/opiniao/tse-tem-oportunidade-historica-de-revelar-os-bastidores-da-publicidade-politica-e-eleitoral-digital/
https://midia.ninja/opiniao/priscilla-a-mulher-do-rei/
https://midia.ninja/opiniao/uma-voz-para-o-brasil-entrevistamos-leci-brandao/
https://midia.ninja/opiniao/a-cultura-voltou/
https://midia.ninja/opiniao/estudo-revela-ameacas-climaticas-nas-favelas-da-mare-ate-2050/
https://midia.ninja/opiniao/males-do-privatismo/
https://midia.ninja/opiniao/nao-podemos-admitir-novos-retrocessos-no-ensino-medio-brasileiro/
https://midia.ninja/opiniao/estudo-revela-ameacas-climaticas-nas-favelas-da-mare-ate-2050/
https://midia.ninja/opiniao/tarcisio-quer-fazer-da-sabesp-a-nova-enel/
https://midia.ninja/opiniao/vitoria-de-milei-e-preciso-compor-uma-nova-cancao/
https://midia.ninja/opiniao/as-redes-sociais-e-sua-responsabilidade-na-violencia-extrema/
https://midia.ninja/opiniao/como-olhar-para-o-futuro-quando-no-presente-nao-nos-aceitam/

- [ ] Investigar e solucionar ou dar retorno interno sobre a autoria das publicações

**Comment by thiagolamonte** [comment]
diagnóstico por links: 

https://midia.ninja/opiniao/qual-a-relacao-entre-a-expressao-de-genero-e-a-violencia-no-carnaval/

neste caso o co-authors "FODA", não está marcado como colunista em PROD. Isso é proposital? Se ele for marcado o card aparece, como mostra a alteração realizada no DEV: 

https://dev.midia.ninja/opinioes/qual-a-relacao-entre-a-expressao-de-genero-e-a-violencia-no-carnaval/

painel do "FODA" em prod
![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/65b7e429-0182-4768-ba56-99598f7691d2)

**Comment by daphnemartinsba** [comment]
Alterações serão realizadas manualmente
Será necessário fazer uma revisão de colunistas
