### ISSUE TITLE
[ARCHIVE EDITORIAS] Ajustar mobile

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#125]
Mobile (Samsung S23 e Iphone Pro Max 14):
- [x] deixar thumb do banner principal igual ao da home
- [x] Samsung S23: thumbs à direita do banner: estão coladas no canto da tela:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/08039793-8ce0-4bb4-b7b6-b9d47b93a68b)

- [x] thumbs à direita do banner: deixar igual à home, somente duas
- [x] Bloco mais lidas está no fim da página
- [x] Samsung S23: tem um bloco que não está carregando
- [x] diminuir distância entre notícias do grid

**Comment by filipesouzadev** [comment]
@daphnemartinsba sobre o bloco mais lidas, o bruno informou que vamos respeitar o empilhamento do HTML

**Comment by caio-ascava** [comment]
Figma:
https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=572-2185&mode=design&t=aev3mbkzn4Uw99Jg-4

S23 e Iphone 14 Pro:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/a7e5d429-763c-46db-b046-89541552bd6c)

- [ ] Ajustar tamanho dos blocos, conforme layout do figma.
- [ ] Sub-categoria e Título no figma tem um espaçamento um pouco maior (com o aumento do bloco vide ação acima)
- [ ] Quanto ao bloco mais lidas, o empilhamento do HTML faz com que este bloco se apresente ao final da tela?
- [ ] Todos os blocos no figma, respeitam os mesmos espaçamentos e estão alinhados entre si.
- [ ] Ao final da tela, as opções devem estar em coluna
- [ ] As datas das postagens no figma estão mais próximas ao título, porem nas imagens anexadas estão mais próximas a imagem da próxima notícia, ficando meio confuso este bloco.
