### ISSUE TITLE
[SEJA NINJA] Ajustes mobile e termos de uso e política de privacidade

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#127]
### Apontamentos do @caio-ascava na issue #83 
- [x] Para mobile, Iphone 14 Pro, os campos de seleção continuam com tamanhos diferentes e também há um espaçamento diferente nestes dois campos (estado e cidade).

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c65e6d5a-db61-415e-bbc7-39b58bc2a509)

- [x]  O Bloco preto A mídia NINJA precisa ser inserida a linha abaixo deste título.
- [x] Aproximar os ícones das redes sociais

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/607909ce-212f-43a0-9df3-85429509b239)

### Demais demandas

- [x] Arredondar borda do bloco SEJA NINJA conforme figma

- [x] Inserir termo de uso e política de privacidade **no DESKTOP E MOBILE:**
- Implemente e estilize **SOMENTE O TERMO DE USO E POLÍTICA** igual ao realizado na página https://midia.ninja/fale-conosco/ 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/2da440e8-b2be-4bbd-9317-b2611df1e0f2)

- [x] Inserir os avisos de falta de preenchimento e bloquear o botão de envio enquanto os campos não forem preenchidos igualmente à página https://midia.ninja/fale-conosco/ 

- [x] alterar background da página para #F5F5F5

**Comment by dioliviers** [comment]
OBS: bloco seja ninja no mobile não tem borda : 
![image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/0ac52481-6531-4dc8-964e-1b36f1b10dca)

OBS-2 : O background ( imagem de fundo ) foi alterado pelo cliente, não é mais a indígena. 
 
 OBS-3 : A Seta não da para alterar no select, tanto mobile quando desktop, cada modelo de celular tem por padrão um modelo de seta e não é recomendável fazer a alteração da seta nativa do dispositivo.
 
 OBS-3 : Não entendi essa (  O Bloco preto A mídia NINJA precisa ser inserida a linha abaixo deste título). Pelo que analisei no layout os blocos estão empilhados conforme o layout.

**Comment by dioliviers** [comment]
O select e input tem particularidades diferentes, porém ajustei a altura e largura padrão para ambos.

**Comment by caio-ascava** [comment]
- [ ] Ajustar responsividade via mobile pois em todas as plataformas testadas, há diferença de layout.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b8b9d9fb-d5d6-4fd4-a350-01765bac912b)

**Comment by caio-ascava** [comment]
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/90e04f2c-50da-4202-a501-ecaf82e4cee3)

**Comment by caio-ascava** [comment]
Foi orientado pelo Diogo que o ajuste foi contemplado no entanto em telas superiores a 360 pixels o texto e ícones de redes sociais ficarão espaçados.
