### ISSUE TITLE
[DESEMPENHO] Otimizações

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#128]
- [x] Converter capas dos especiais em JPEG/WEBP.

- [ ] Hospedar o compartilhamento: atualmente usa o plugin addtoany https://static.addtoany.com/menu/page.js, deixar de usá-lo e hospedarmos 

- [x] Configurar o plugin do reCAPTCHA

- [x] Investigar como corrigir o favicon, ele é bem grande

**Comment by Thayna-Zacharias** [comment]
Para a conversão de formato das capas dos especiais, foi instalado o plugin 'webp express' que faz a conversão de todas as imagens para o formato webp e foi desativado o plugin modern image formats.

**Comment by Thayna-Zacharias** [comment]
A imagem do favicon foi passada pelo site tinypng, o que modificou o tamanho da imagem de  157kb para 17kb.

**Comment by Thayna-Zacharias** [comment]
Otimizei a imagem do favicon em dev, diminuindo o tamanho da mesma de 157kb para 32kb mantendo no formato png com transparência

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/073cec01-aecc-467b-9837-54b7504b1c91)

**Comment by Thayna-Zacharias** [comment]
O item de hospedagem de compartilhamento é uma demanda de código. 
O script é inserido no plugin, mas é uma URL remota para um servidor que demora para responder. Se possível substituir por uma URL local (basicamente "vendor-ar" o script).
Se o handle for tal, substituir a URL por outra.

**Comment by daphnemartinsba** [comment]
issue de hospedagem de compartilhamento #165
