### ISSUE TITLE
[NEWSPACK] Ajustar configurações

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#13]
- [x] Configurar Newspack para listar os cpts criados no PODS: Opinião, Especiais, Afluentes, Galeria.
- [ ] Remover CPTS desnecessários.

**Comment by everaldomatias** [comment]
Feito @estercmandrade

**Comment by everaldomatias** [comment]
@daphnemartinsba qual o cpt que está faltando aqui no Homepage Articles (do Newspack Blocks)?

![Image](https://github.com/midianinja/ninja-wp-theme/assets/1918474/2d21f8ff-8144-40e6-87fb-1e8408921e70)

**Comment by everaldomatias** [comment]
Todo CPT registrado via código ou por plugin (ex. Pods) deve aparecer nessa lista de opções do bloco Homepage Articles (do Newspack Blocks).

**Comment by daphnemartinsba** [comment]
CPTs serão removidos na issue: #49
