### ISSUE TITLE
[LEGENDA DA FOTO] SINGLE de NOTÍCIA, OPINIÃO E GALERIA

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#130]
- [x] estilizar legenda da foto para ficar de acordo com o figma, deve ser aplicada para as singles no geral
Layouts de exemplo:
- Galeria: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=605-1907&t=bOP8ga5iyYegtLzI-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- Notícias https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-12861&t=bOP8ga5iyYegtLzI-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Verificar blocos de galerias e imagens

**Comment by daphnemartinsba** [comment]
CPT Galeria:
- [ ] Alinhar à esquerda com o bloco de imagem, deixando conforme o figma (no momento está à esquerda, mas não está totalmente alinhado)
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d42cf25d-fde4-449f-9408-526248613931)

- [ ]  alterar line height da fonte para 21px

**Comment by daphnemartinsba** [comment]
- [ ] Legendas grandes extrapolam imagens nas galerias

**Comment by thiagolamonte** [comment]
validação: 

https://dev.midia.ninja/galeria/justica-climatica/

Nas singles de galeria:

Observando o Layout, temos ali um espaço para crédito das fotos. Orientar o cliente que a legenda das fotos não pode passar de uma linha para manter o grid de galerias conforme o Layout. 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/57574274-745b-47b9-9c2b-902a82cc30a0)


![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/0e556eaa-cec1-42da-a99d-3ae1da93d2c3)

**Comment by thiagolamonte** [comment]
Minha proposta é orientar o cliente que as legendas de imagens de dentro do bloco de galeria não devem ultrapassar uma linha. A quantidade de caracteres pode variar de acordo com a quantidade de imagens por linha. Isso irá garantir que o grid das galerias galerias mantenham um padrão no projeto. Nas imagens do bloco de imagem normal é possível colocar a legenda do tamanho que for necessário
