### ISSUE TITLE
[PÁGINA COLUNISTAS] Paginação

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#133]
- [x] Implementar paginação no bloco Mais colunistas NINJA na página Colunistas

**Comment by thiagolamonte** [comment]
tarefa em andamento, paginação aplicada porém os posts estão duplicando

**Comment by thiagolamonte** [comment]
validação:

aplicado e tema atualizado no dev
https://dev.midia.ninja/colunistas/
