### ISSUE TITLE
[SINGLE FOTOGRAFIA] Revisar/ajustar CSS

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#136]
- [x] desktop
- [x] mobile
- comentar os ajustes necessários

**Comment by dioliviers** [comment]
Em call com o @caio-ascava 
Verificamos que cada single tem um comportamento diferente do layout, chegamos a conclusão que cada editor, como ele cria single com o conteúdo daquele acervo de fotografias o próprio irá definir a quantidade de imagens, inseridas e o texto. 

Oque foi feito : 

Ajustado a resolução para todos os tipos de imagens e oos assets para ver se está batendo com o layout, não focando na ordem das fotografias e sim na qualidade e no padrão dos dextos inseridos.
