### ISSUE TITLE
[SINGLE OPINIÃO] Revisar e ajustar CSS

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#137]
- [x] desktop
- [x] mobile
- comentar aqui o que foi feito

**Comment by dioliviers** [comment]
Aparentemente está conforme o layout: 
Dev : 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/7933a0f8-f2dc-451a-9bf1-1ece41df9043)


Layout : 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/7ea3cefd-3bad-435a-99da-31be5102283f)

Obs : levar em consideração de que os icones de redes sociais estão com o formato ' betweeen' por conta de ( responsividade )onde eles ficam com um espaço maior entre os elementos e conforme a tela vai diminuindo a largura ele irá se adaptando.

Em call com o @caio-ascava , temos dois layout de colunistas, com CARD ou quando não é colunista aparece da seguinte forma : 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/7fc6573e-f92b-4b3a-9f64-ca9f5e456fe3)

Porém não encontramos usuários que não sejam colunistas no prod somente no dev ( verificar com o gestor do projeto a ausência de colunistas na single de opinião, se é um comportamento comum ).
