### ISSUE TITLE
[AFLUENTE] ESTUDANTES NINJA: bloco de vídeo

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#140]
- [x] Alterar bloco para listar as thumbs com os títulos
- [ ] Ter slide caso tenha conteúdo suficiente

**Comment by caio-ascava** [comment]
- [ ] Bloco foi alterado, porem precisa ajustar seu layout. Com a Thumb da noticia ao lado esquerdo e ao lado direito desta, o título.
- [ ] Ajustar fonte de "OPINIÃO" e "QUEM SOMOS", design tokens/FIGMA.
- [ ] Algumas thumbs possuem borda retangular e maioria redonda. Precisa padronizar todas com bordas redondas

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/2653c588-da6e-4ad0-ad5b-04714de4db72)

**Comment by daphnemartinsba** [comment]
retornos acima serão considerados como ajustes finos, ajuste no bloco de vídeo na issue #171
