### ISSUE TITLE
[SINGLE OPINIÃO] componente do co authors direcionar para colunista

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#142]

**Comment by thiagolamonte** [comment]
validação: 

funcionalidade aplicada no ambiente Dev - Não foi feito release em PROD: 

https://dev.midia.ninja/opiniao/jornada-de-lutas-em-defesa-da-reforma-agraria-do-mst-levanta-coro-ocupar-para-o-brasil-alimentar/

clicar no logo, nome ou bio do colunista

**Comment by daphnemartinsba** [comment]
está direcionando para a página de colunista no dev.midia.ninja
