### ISSUE TITLE
[HOME] mobile do bloco de vídeo e imagem de destaque da home

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#143]
- [x] centralizar vídeos do youtube no mobile:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/4b304b5d-5a34-4e4e-b51b-94ac1c4ae9c4)

- [x] Ajustar qualidade da imagem de destaque da home: mesmo que a imagem tenha uma boa qualidade, ela é exibida como se não tivesse

**Comment by barbaburns** [comment]
Manter mesmo estilo mobile para tablet, mudando apenas em desktop.

**Comment by thiagolamonte** [comment]
o bloco de destaque ta home tem 900 x 500 qualquer imagem com dimensões menores que essas irá perder qualidade ao ser renderizada no bloco.

**Comment by daphnemartinsba** [comment]
Fazendo uma postagem com uma imagem de 1280 por 853 px. 
Enquanto a imagem da home fica levemente embaçada:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a649d4fa-a361-4787-86c4-d58db056f31b)

A da single mantém a resolução da imagem original:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/6c1b71a4-0e24-4249-ae1e-35ea5bf53b0c)

Exemplo:
https://dev.midia.ninja/teste-thumb-da-home/
https://dev.midia.ninja/

**Comment by thiagolamonte** [comment]
com a volta da issue para revisão foi iniciado um debug no código do newspack pra tentar entender porque que a escolha do tamanho da thumb na config do bloco não esta funcionando. Se troca de L pra XL nada muda no html, ele sempre renderiza o 800 X 600. Por isso qualquer imagem que entra, mesmo sendo maior, perde qualidade.

**Comment by daphnemartinsba** [comment]
issue sobre imagem de destaque #153
