### ISSUE TITLE
[ARCHIVE OPINIÃO] Ajustes no bloco TODOS OS COLUNISTAS no MOBILE

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#144]
- [ ] Mobile Samsung, Iphone e Ipad: bloco conheça todos os colunistas está sem slide e mostra mais de dois colunistas, botão está cortado:
 
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e851201e-3b72-4f12-b6ba-b8c0fec3c7f8)

- [x] botão todos os colunistas deve direcionar para /colunistas

Ajustes finos mapeados que não são prioritários:
-  Mobile Samsung S23: listar somente 8 colunistas no grid, acima de mais lidas
- Bloco mais lidas: muda de tamanho conforme título da postagem muda de tamanho
- alinhar bloco mais lidas ao título das postagens
- Mobile Samsung S23: segundo bloco muda de tamanho conforme muda slide

**Comment by dioliviers** [comment]
OBS: lembrar de inserir o bloco na pagina OPINIAO no prod também, no momento só funciona no dev

**Comment by caio-ascava** [comment]
Lembrete:  tem que inserir o link de direcionamento da pagina de todos os colunistas na archive de opinião.
