### ISSUE TITLE
[AFLUENTES] Cine Ninja - Pendências complementares

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#145]
- [x] Traçado branco (linha) deve ficar mais próximo ao Cine Ninja (quase que um sublinhado, consultar Figma)
- [x] Os ícones das redes sociais também estar mais alinhados à esquerda no Figma e menos espaçados.
- [x] nesta postagem por exemplo, o termo CRITICA sumiu do post (bloco cinza à esquerda)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b2c59601-064f-45f2-be61-d056a5688b36)

- [x] Mobile: Ajustar estilo de premiações:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/b7428a93-dcb0-4b4e-801e-417915a85248)

- [ ] Mobile: thumbs de estréia da semana não está com qualidade adequada:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/aefa7708-7965-4ca1-8ee4-22c440a5002f)

**Comment by dioliviers** [comment]
Ps: A maioria dos ajustes solicitados já estão resolvido, ficou uma questão das premiações que não estava ajustado agora já ajustado.

**Comment by caio-ascava** [comment]
- [ ] Ajustar o bloco embaçado conforme layou do Figma;
- [ ] Inserir título "Crítica" (apresentado anteriormente)

**_Alterações identificadas que não serão realizadas:_**
- Bloco CineNinja terá layout igual ao desktop

- [ ] Ajustar a linha branca abaixo de Cine Ninja
- [ ] foi identificado que o bloco "ESTREIAS DA SEMANA" não aparece mais em mobile

_Alterações identificadas que não serão realizadas:_
- No Figma, as THUMBS com as noticias estão após todos os blocos (final da tela), mas este comportamento será utilizado do WP mesmo, em que as noticias (thumbs vem após sub menu)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/08f1fb17-0829-4808-8c16-889d3a38cc9e)

**_Alterações identificadas que não serão realizadas:_**
- Após as thumbs com noticias no figma há um botão de "ler mais notícias, mas seguirá no formato de slides.
- Bloco Cine Ninja Indica será com 3 thumbs, descrição e autor.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/bec919d1-d3df-45b6-9e1c-c90f573d27e7)

- [ ] Bloco de premiações está em formato de slides, mas em dev. estão inserido com largura comprimida em única tela.
- [ ] Bloco "quem financia a Mídia Ninja é você tem cor diferente e com texto e botão centralizados.
- [ ] Fonte de quem somos precisa ajustar
- [ ] Avaliar se não haverá bloco de "ESPECIAIS"
- [ ] A imagem que tem abaixo do texto de quem somos, é ampliada (Figma), pegando a tela em sua largura total.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/5254482a-1f02-4b17-9696-fd1d98ce4199)

**Comment by daphnemartinsba** [comment]
- O bloco de Premiações foi substituído pelo de vídeos. A título de mapeamento de ajuste fino, o bloco segue assim no mobile:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e77f6cfa-3aaf-4bb9-8cb3-40a5cd0482e5)

As demandas apontadas acima serão consideradas também como mapeamento de ajustes finos
