### ISSUE TITLE
[SINGLE NOTÍCIAS] Correções pontuais

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#146]
Desktop
- [ ] Ajustar formato de horário após data da publicação com ícone de relógio antes do horário e formato HHhMM (19h40).

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/69bec5f8-6187-4606-b931-dab4e3955013)

Mobile
- [ ] Ajustar linha branca para abaixo de Planeta Foda.
- [ ] Ajustar formato de horário após data da publicação com ícone de relógio antes do horário e formato HHhMM (19h40).

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1a9bbea8-cd34-4432-94ca-709f30be25dd)

**Comment by daphnemartinsba** [comment]
Os apontamentos dessa issue devem ser considerados como mapeamento de ajustes finos. O ajuste na quebra das legendas com mais de uma palavra será realizado na issue: [#169](https://github.com/midianinja/ninja-wp-theme/issues/169)
