### ISSUE TITLE
[TV NINJA] Shorts

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#148]
- [x] Slide deve puxar mais de 5 shorts
Ao marcar para mostrar 5 shorts ele deixa de ter o comportamento de slider

- [x] No mobile: shorts tem mais slides que vídeos 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a1f79514-34a2-4c65-b82f-64e16c0ca4eb)

- [x] Bolinha do slider deve ter cor diferente para indicar em qual slide o usuário está

**Comment by thiagolamonte** [comment]
validação

https://dev.midia.ninja/tv-ninja/

obs: para resolver o clique correto nas setas do slider no mobile foi feita uma proposta de layout mostrando uma thumb por vez
