### ISSUE TITLE
[SEJA NINJA] Criar página e formulário seja ninja

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#15]
- [x] Configurar ReCaptcha v3
- [x] Criar página e estrutura (inclusive formulário)
- [x] Aplicar layout com estilo

Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=467-2825&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=467-2906&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by caio-ascava** [comment]
- [ ] Aplicar fundo de quadro cinza claro, conforme Figma, na caixa de texto (ao lado esquerdo)

- [ ] O campo de Cidade no Figma parenta-se como um campo de preenchimento, porem em DEV está como lista suspensa.

- [ ] Aumentar espaçamento entre "inscrição" "Seja Ninja" e "texto"

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1c37a418-efc4-49a5-920a-4cdb66d8c6c3)

**Comment by dioliviers** [comment]
Ajustado o blur  da imagem ela está mais opaca 
Ajustado o distanciamento entre os titulos 
Foi verificado com o designer que haverá uma flecha para baixo apresentando os itens do select .

**Comment by dioliviers** [comment]
Update : Foi autorizado a flecha do select neste modelo, o do layut foi feito erroniamente, conforme descrição do designer Pedro.

**Comment by daphnemartinsba** [comment]
- [ ] Adequar à seta do figma atualizado

**Comment by daphnemartinsba** [comment]
blocked: staging diferente do dev e do local

**Comment by daphnemartinsba** [comment]
Retorno em #83
