### ISSUE TITLE
[NEWSPACK ADS] Debug registro credências do plugin de anúncios.

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#150]
Tentamos configurar o plugin NEWSPACK ADS para anúncios, mas em inserir o arquivo JSON com as credências, o plugin deu um erro fatal e não conseguimos mais ativar o plugin.

- [x] Identificar onde o plugin NEWSPACK ADS registra as credências e limpar essas configurações.

- [x] Testar habilitar o plugin novamente.

**Comment by thiagolamonte** [comment]
plugin atualizado para a versão 1.48.0
