### ISSUE TITLE
[NEWSPACK] Atualizar plugin em dev para testes

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#151]
- [x] Atualizar plugin em dev para testes

- [x] Verificar se páginas com blocos newspack continua funcionando.

**Comment by thiagolamonte** [comment]
Foi atualizado o plugin para a ultima versão 3.8.4



![Image](https://github.com/midianinja/ninja-wp-theme/assets/53320806/bceb24d4-95e1-4192-a6d6-fd2f23125979)



Home funcionando
