### ISSUE TITLE
[FALE CONOSCO] Redes sociais MOBILE

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#155]
- [x] Ajustar ícones de redes sociais (em mobile aparece apenas o Instagram)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/4992b919-d17a-4ff2-8bc9-ad952164a79f)

**Comment by dioliviers** [comment]
resolvido : https://midia.ninja/fale-conosco/
