### ISSUE TITLE
[AFLUENTES] Mobile - single

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#159]
Foi identificado que entre os afluentes não possui um padrão do menu alternativo. No entanto, foi avaliado a funcionabilidade das arquives. Caso seja possível e necessário, ajustes finos a serem realizados:

- [x] Ajuste fino em todas as archives para customização da fonte ninja de "QUEM SOMOS", conforme FIGMA, elas deveriam estar na fonte ninja.

_Os ajustes mapeados abaixo são referentes ao menu alternativo que em alguns casos apresenta-se colado ao bloco superior. Embora não possua um formato padrão deste menu alternativo, os apontamentos inseridos abaixo são necessários._

- **Casa NINJA Amazônia**
Nenhuma alteração, apenas para registrar o formato do menu alternativo.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1f17a952-c5b1-4d83-b097-371b12786370)
**- Cine Ninja**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/be5e98e1-e6fd-45f8-b19a-9c1d0116eaa1)
**- Design Ativista**
- [x] Diminuir recuo entre blocos
- [x] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/31c1aa7d-9004-4b29-8f1f-3093c80a0c9f)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/12515b0c-ceb2-49ff-9cad-0a35dde4b233)
**- FODA**
- [x] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/d776442b-3f0c-4298-ba87-d1b97d9a618d)
- NINJA Esporte Clube
Nenhuma alteração, apenas um novo formato de menu alternativo.
**- ELLA**
- [x] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/109df57d-c325-4550-9494-c1f12cb6938f)
**- Poderes Pretos**
- [x] Diminuir recuo entre blocos
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/751f8fc7-07c1-4ab1-b8af-037574a5bd3c)

**Comment by dioliviers** [comment]
Casa amazonia - Problema com sobreposição de menu ajustado em DEV e PROD, ou seja no mobile não vai mais aparecer as 3 risquinhas no menu, ajustado distanciamento entre avatar e h2 .
Poderes pretos, ella, foda, ajustado espaçamento dentre os blocos no modo mobile 

OBS: sobre os menus todos os afluentes que fui achando fui ajustando no menu para desativar a sobreposição de menu, caso haja caso semelhantes basta desativar essa opção : 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/e476c607-e553-4320-b5b7-1fe1bacee219)


Fiz alguns ajustes no local, já enviando para o dev e fazendo os ajustes no painel do menu, porém acredito que vamos ter que fazer os mesmos ajustes em prod no painel também, com relação ao menu.
