### ISSUE TITLE
[TV NINJA] Criar bloco para playlist de vídeo

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#16]
https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1376-3884&t=bHCMn94EredvF40z-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
- [x] Investigar se é possível:  Ao dar play no vídeo em destaque, o vídeo deve reproduzir na tela

**Comment by thiagolamonte** [comment]
https://dev.midianinja.org/videos-midia-ninja/

Fizemos uma outra proposta, de usar o bloco de playlist de vídeo que usamos em outros projetos

**Comment by caio-ascava** [comment]
- [ ] Alterar botão Play do youtuube de retangulo vermelho para circulo cinza.
- [ ] Dentro do bloco vídeos, os próximos vídeos não estão inseridos como lista suspensa, mas uma prévia do próximo. 
- [ ] Na resolução 1366, precisa alinhar o bloco maior, VIDEOS, quase que no mesmo espaçamento que o ícone de instagram, no cabeçalho. 
- [ ] E o bloco da direita, MAIS VIDEOS, quase que no mesmo espaçamento que o ícone da lupa, no cabeçalho.
- [ ] Os videos dentro do bloco "MAIS VÌDEOS", no Figma arace dentro da miniatura o tempo referente a duração de cada vídeo.
- [ ] Logo abaixo destes 02 blocos, no Figma possui mais vídeos a serem exibidos, no entanto, no staging ele segue para "SHORTS".
- [ ] Quando eu clico em mais vídeos no bloco da direita, ele direciona diretamente para a pagína no youtube, saindo do site do midia ninja. 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/6ccbe65b-d8ee-438f-9f61-4e5c3db1a729)

- [ ] Na resolução 1920, precisa alinhar o bloco maior, VIDEOS, quase que no mesmo espaçamento que o ícone de instagram, no cabeçalho. E o bloco da direita, MAIS VIDEOS, quase que no mesmo espaçamento que o ícone da lupa, no cabeçalho.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/6b17b6c2-f29b-4464-920b-7e76e2ae74da)

- [ ] Alterar ""Assine nossa newsletter" quebrado em 3 linhas, para duas. Assim como, o texto abaixo desta.
- [ ] Não sei se é coincidência dos vídeos, mas no Figma todos os Shorts possuem a legenda padronizada ma mesma posição, porem no novomidianinja não há padrão.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/68e56544-d6b2-41e6-b52e-06e67ea4765e)

**Comment by marinarcruz** [comment]
o modal será feito por plugin

**Comment by daphnemartinsba** [comment]
Haverá alterações no layout, será resolvida na #95
