### ISSUE TITLE
[DOCUMENTAÇÃO] Criar novo modelo de página âncora para página de documentação.

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#164]
- [x] Criar novo modelo de página âncora para página de documentação.
- [x] Estilizar índice da página.

**Comment by thiagolamonte** [comment]
https://dev.midia.ninja/documentacao/

**Comment by daphnemartinsba** [comment]
Modelo de âncora:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/a30bf8f8-19ff-4113-ad56-bd6514ed9481)

![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/72182d3f-d044-482f-a760-97540985cf0d)

Ao clicar na âncora, ela direciona para o título
