### ISSUE TITLE
[CINE NINJA] Thumb dos blocos cine indica e estreia da semana no MOBILE

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#166]
- [x] ajusta imagem da thumb no desktop e no mobile

**Comment by thiagolamonte** [comment]
validação:

https://dev.midia.ninja/afluente/cine-ninja/

**Comment by daphnemartinsba** [comment]
Imagem ficou mais adequada no mobile:

Dev:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/b8540590-d954-4957-bb20-c4c8bc4c72a5)


Mobile dev:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/5f9beebc-ec15-4523-9137-08077ffcd859)
