### ISSUE TITLE
[SINGLE FOTOGRAFIA] Bloco de galeria no mobile

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#167]
- [x] No mobile galeria com duas imagens ficam muito espaçadas:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/01e060d7-a91b-4631-9ae0-369a1759eadc)

**Comment by dioliviers** [comment]
Gap retirado na versão mobile para 0px, onde as fotos miniaturas ocupam o distanciamento padrão.

**Comment by caio-ascava** [comment]
Como um ajuste fino que pode ser realizado posteriormente, ficará pendente (após uma avaliação holística do site):

- [ ] Redução do espaçamento entre as 2 miniaturas 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/a56333aa-41ee-4369-b479-fc4bc0c326f4)
