### ISSUE TITLE
[AFLUENTE] ESTUDANTES NINJA: MOBILE do bloco de vídeo

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#171]
- [x] Bloco de vídeo está cortado e fica com a thumb cortada:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/994424e7-e864-43ac-8f52-f7873fce0a4a)

**Comment by thiagolamonte** [comment]
https://dev.midia.ninja/afluente/estudantes-ninja/
