### ISSUE TITLE
[AFLUENTES] Bloco de destaque

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#172]
- [x] Alterar bloco de destaque: utilizar o novo bloco de destaque da home
https://www.figma.com/design/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?node-id=7036-8557&t=Dgy5oxNr3Cca8yZK-0

**Comment by marinarcruz** [comment]
- [ ] Bloco principal dos afluentes deve apresentar as últimas notícias, como na home

- [ ] Fazer ajustes de CSS nas páginas dos Afluentes:
- [ ] Cine Ninja
- [ ] Design Ativista
- [ ] NEC

Aplicar estilo de degradê também na archive de afluentes: https://dev.midia.ninja/afluente/

**Comment by marinarcruz** [comment]
Todos validados, com exceção de ajustes no Cine Ninja e Design Ativista. Alinhamento tamanho blocos da dobra principal.

É preciso aplicar o degradê para a archive de Especiais também: https://midianinja.org/especial/ . o texto e imagem são fixos.

**Comment by barbaburns** [comment]
a ordem dos blocos tb esta diferente em mobile. usando cine ninja como exemplo, no figma "estreias da semana", "cine indica" e "circuito de formação" vem antes do grid de posts.

**Comment by barbaburns** [comment]
no figma, o card de afluentes em mobile fica sem o texto de excerpt, porem não esta assim no dev.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/11669690/82cb58bb-e5ea-4f2b-9689-4b183d252e0c)
