### ISSUE TITLE
[LIMITE DE CARACTERES] HOME

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#178]
- [x] Aplicar limitação de caracteres no título e no resumo para não quebrar o layout

**Comment by barbaburns** [comment]
Adicionei uma regra de limite de caracteres apenas pra home, limitando o titulo a 50 caracteres e o resumo a 150.

**Comment by Thayna-Zacharias** [comment]
Verificar nas configurações padrão do wordpress se o mesmo está limitando os caracteres abaixo de 100.


![Image](https://github.com/user-attachments/assets/4332806d-2797-42bd-9ad6-6b5b0029dd23)



![Image](https://github.com/user-attachments/assets/fe3724dc-6f36-47ef-b49a-a9ef49e55a9e)

**Comment by thiagolamonte** [comment]
os limites são definidos nessas duas funções no arquivo utils.php: 



![Image](https://github.com/user-attachments/assets/74659c76-7756-47b9-950b-feec21ef7bd2)

**Comment by Thayna-Zacharias** [comment]
Os posts voltaram a limitar os caracteres abaixo de 100, mesmo estando no arquivo para que o limite seja de 108 


![Image](https://github.com/user-attachments/assets/0c8fab66-9aaa-419e-b6f4-0f3b791801b2)



![Image](https://github.com/user-attachments/assets/dfa5137c-1f31-4578-8f87-d53ea3995314)



![Image](https://github.com/user-attachments/assets/2cdf3a4c-2ecf-4e42-8b32-f37d7a67a6a4)

**Comment by barbaburns** [comment]
O limite de caracteres esta funcionando bem no meu localhost e no dev, não consegui reproduzir o problema.
