### ISSUE TITLE
[SINGLE DE OPINIÃO] IMAGEM DE DESTAQUE

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#179]
- [x] Estudar possibilidade de remover imagem de destaque das colunas antigas e daqui pra frente habilitar.

- [x] Nas novas colocar um check-box para quando exibe a imagem na matéria. (Possibilidade de aplicar imagem genérica para todos os colunistas. - editorial a partir das novas. Muito complexo fazer automaticamente)

- [x] Investigar se é possível alterar essa imagem nos novos post.

- [x] Testar em Dev exibição da single como está a single de notícias para a partir de agora.

**Comment by marinarcruz** [comment]
03/6: testaremos plugin. Exige análise maior.
Prioridade de aplicação para o segundo checkbox dessa issue.

**Comment by Thayna-Zacharias** [comment]
Referente o item 1: É possível remover a imagem de destaque, pois o checkbox está disponível em todos os posts de opinião, sendo que os anteriores não estão ticados, logo, não aparecerá imagem de destaque dentro da publicação.

Referente ao item 2: Checkbox aplicado em todos os posts de opinião, sendo uma tarefa editorial ticar o campo e eleger a imagem genérica

Referente ao item 3: É possível alterar a imagem nos novos posts, sendo uma tarefa editorial.



https://github.com/midianinja/ninja-wp-theme/assets/145383848/5536084b-f141-4aa3-8ffd-46dcc4241db1

**Comment by laurahacklab** [comment]
@Thayna-Zacharias Validados os 3 itens, porém a página está ficando quebrada, com ou sem a imagem:

Com:
![image](https://github.com/midianinja/ninja-wp-theme/assets/109294895/47e9d8bc-a5de-46eb-81a9-89436dc23ec3)

Sem:
![image](https://github.com/midianinja/ninja-wp-theme/assets/109294895/57c4e0f0-80b2-43e4-b423-b7b0327ffc68)

**Comment by marinarcruz** [comment]
12/06: precisaremos dedicar um dev a partir da semana que vem

**Comment by Thayna-Zacharias** [comment]
O checkbox foi implementado com o pods, e quando a marcação é feita, a imagem é implementada dentro do post.

**Comment by Thayna-Zacharias** [comment]
https://github.com/midianinja/ninja-wp-theme/assets/145383848/72c42205-9007-41d7-9bb5-daece712f55b

**Comment by Thayna-Zacharias** [comment]
Implementada imagem de destaque na single de opinião, que aparecerá no início do post quando a opção do checkbox estiver setada


![Image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/23475e3f-5702-4755-9102-99af2c822bb3)

**Comment by caio-ascava** [comment]
- [ ] Bloco do colunista com sua descrição está quebrado devido a falta de limitação de caracteres, e os ícones das redes socias não aparecem.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b662d3a2-1463-47f4-b794-def5867472c4)

- [ ] Em mobile, S23:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/74ac664d-0c4b-4071-ae7c-f785ffbf1cd4)

- [ ] Em mobile, Iphone 14 Pro
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c240bba7-a961-453c-ada1-5f425e1d770e)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/7ecbc1b9-bb93-4db1-9ae8-273690bad630)

**Comment by caio-ascava** [comment]
https://dev.midia.ninja/opiniao/aqueles-que-ficam-para-tras/

- [ ] Ao compartilhar o link no whastapp, a thumb que aparece é a do midia ninja, mas deveria aparecer a thumb (imagem destaque) da opinião.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/a3e813e9-0d59-452a-a5f8-995afa772098)
