### ISSUE TITLE
[TV NINJA] Aplicar layout, estilo e responsividade

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#18]
url da página Satgin:

https://novo.midianinja.org/videos-midia-ninja/

**Comment by daphnemartinsba** [comment]
plugin para modais: Elfsight YouTube Gallery CC

**Comment by thiagolamonte** [comment]
validação:

https://novo.midianinja.org/videos-midia-ninja/

O estilo do Desktop foi possível atender, com pequenas ressalvas. O plugin não mostra dots entre as setas dos sliders. A paginação não mostra a seta de "prev", inicia na página 1. 

No responsivo, o plugin coloca apenas 1 card por slider.

**Comment by daphnemartinsba** [comment]
Haverá alterações no layout, será resolvida na issue #95
