### ISSUE TITLE
Atualização diária do bloco Mais Lidas

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#185]
Atualmente o bloco Mais Lidas da home atualiza diariamente considerando os posts mais acessados dos últimos 15 dias.
Adicionar ao código uma condicional que considere os posts mais acessados do dia. 
![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/32d2a804-e062-453d-8dfe-62cf0010e9ea)

**Comment by barbaburns** [comment]
Não consigo mexer no backend desse bloco para fazer essa modificação. Posso acompanhar o @everaldomatias nessa tarefa.

**Comment by everaldomatias** [comment]
Implementei, com apoio do Rafa, a alteração no dev, para testarmos.

Fiz no bloco horizontal, quando validarmos, aplico para o vertical também.

Como agora o bloco de mais lidas exibe apenas posts de hoje, criei um post aleatório para que seja possível visualizar o bloco em funcionamento (na home do dev).

Outra informação, as visualizações dos posts só são contabilizadas para usuários deslogados, caso precise testar a quantidade de visualizações.

Quando o funcionamento desse bloco estiver validado, aplico nas outras versões e commito nos branchs definitivos (por enquanto criei em branchs específicos para essa funcionalidade).

**Comment by Thayna-Zacharias** [comment]
![Image](https://github.com/user-attachments/assets/1a78cd3f-43b3-4f10-8d44-66033d4356b1)

A atualização do plugin Ajax Pageview para a versão 2.0.3 não funcionou, de forma que o frontend só carrega como cache do cloudflare.
Como já informado pelo Everaldo que teve orientações do Rafael para essa atualização, as requisições deixariam o plugin pesado de forma que impactasse muito na performance do site. 
Necessário avaliação para otimização do plugin com apoio do Jacson ou Rafael, de acordo com report do Everaldo no canal. Após esta ação o bloco deverá atualizar diariamente como esperado.

**Comment by laurahacklab** [comment]
Não daremos continuidade, vamos manter como estava antes. Bruno irá fazer a comunicação ao cliente.
