### ISSUE TITLE
[FOTOGRAFIAS] Criar estrutura da página e das guias na ARCHIVE

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#19]
Na primeira dobra:

- [x] Implementar slider
- [x] Destaque: galeria de fotos

Guias:
- [ ] implementar guia seletas com thumbs de clássicos ninjas e etc
- [ ] implementar guia acervo com thumbs com thumbs (redirecionamento para url do album no flickr)

**Comment by barbaburns** [comment]
Precisam ser desenvolvidos blocos para  o conteudo do cpt e para os albuns do flickr.

**Comment by marinarcruz** [comment]
precisa de ação do @everaldomatias

**Comment by daphnemartinsba** [comment]
- [ ] Alterar cor da bolinha do slide
- [ ] Quando o slide não puder ir para a esquerda ou direita, alterar cor da bola e da seta, padronizar conforme slider da home 

- [ ] Mobile: aumentar distância entre thumbs do acervo
- [ ] Mobile: Ajustar slide conforme figma
- [ ] Mobile: aumentar espaço entre itens de paginação, para ficar conforme figma

**Comment by caio-ascava** [comment]
Ajustar a cor da bolinha e seta, conforme Figma.

Em dev e prod, quando você passa o mouse pelas setas elas ficam escuras. Diferentes do comportamento em outras singles.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c4294ce1-53ac-431b-8548-866a99cf2db4)

**Comment by daphnemartinsba** [comment]
Retornos foram dados na issue [#170](https://github.com/midianinja/ninja-wp-theme/issues/170). Demais apontamentos devem ser considerados como mapeamento de ajustes finos
