### ISSUE TITLE
[POSTS] Tags e bloco de parágrafo sumindo durante edição

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#196]
Durante edição de posts, as tags adicionadas somem e tem de ser adicionadas novamente, sem que tenha sido salvo o post, o mesmo ocorre quando um bloco de parágrafo é adicionado e ocorre copia e cola de textos do chat GPT, por exemplo, o bloco some sem que seja feita essa ação.

OBS: Conseguimos reproduzir o erro com o navegador do google chrome.

**Comment by Thayna-Zacharias** [comment]
![Image](https://github.com/user-attachments/assets/56bdcb28-f978-413e-aeac-20336067d277)


![Image](https://github.com/user-attachments/assets/d73d85fe-b6ac-4be8-883b-e1f1c6232422)

verificar se esses erros que ocorreram ontem (06/08) durante edição de posts estão relacionados com o problema de carregamento das taxonomias

**Comment by marinarcruz** [comment]
13/8: não há ajustes de código envolvidos, é preciso que a infra esteja melhor.

**Comment by marinarcruz** [comment]
Report: ainda há tags sumindo durante a edição. Orientação: quando acontecer novamente, filmar e acionar o suporte para conseguirmos identificar como atuar (chamada).
