### ISSUE TITLE
[CABEÇALHO]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#2]
Layout do figma - desktop:
https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=562-355&mode=design&t=iYdVRgjdhhwlXRD7-0

Layout do figma - menu hamburguer - desktop e mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-11048&t=8squyVQ6kst1CKLh-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Layout do figma - mobile:
https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=562-1389&mode=design&t=iYdVRgjdhhwlXRD7-0

Layout do figma - mobile - menu aberto:
https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=2094-2720&mode=design&t=M8t4D5Vvmn0WfGNC-0

- [x] Cabeçalho
- [x] Busca com funcionamento de buscar
- [x] hamburguer com funcionamento

**Comment by caio-ascava** [comment]
No desktop, quando eu clico na lupa de buscas e fecho a janela, ao retornar ele permanece desta forma até que clique em outro lugar da página.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/162548a7-7f32-47e5-8df0-00bacc180857)

**Comment by daphnemartinsba** [comment]
#### Complemento do QA
**Desktop**
- [ ] Resolução 1920 e 1366 - Encostar menu na lateral direita
- dev - 1920:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/f941d3f4-5f69-45fc-b52e-80fab90bcacd)

- [ ] Retirar barra de rolagem
- [ ] 1920: Ao rolar a tela para baixo, menu deve preencher tela
 dev: 
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/ac4cf92d-62c1-4000-b56d-fb9cd5458872)

- [ ] Alterar line height da fonte dos subitens para 16.8px
- [ ] alterar line height dos itens para 28.8px
- [ ] Alterar cor das bordas (divisórias) para #848484
- [ ] Adequar tamanho dos ícones de redes sociais

**Comment by caio-ascava** [comment]
Retornos de validação serão resolvidos na Issue #55
