### ISSUE TITLE
[SINGLE FOTOGRAFIAS] Criar página e aplicar layout de CLÁSSICOS NINJA

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#20]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=605-1907&t=acF2NbcUHAQjXyZW-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=608-2394&t=acF2NbcUHAQjXyZW-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by barbaburns** [comment]
Foi decidido que a newsletter fara parte do rodapé, então esta single esta finalizada.

**Comment by caio-ascava** [comment]
Desktop
- [ ] Reduzir espaçamento entre a imagem destaque e título "Clássicos Ninja"
- [ ] Reduzir espaçamento entre imagens (vertical e horizontal)
- [ ] Após a inclusão das 04 imagens em formato de galeria, elas alteram o layout padrão, sendo que ao invés formato 2x2 estava aparecendo como 3x1.
- [ ] No bloco em que são 04 imagens miniaturas, 4x4, elas aprecem 3x3x2.

**Comment by caio-ascava** [comment]
Para melhor visualização https://github.com/orgs/midianinja/projects/3/views/1?pane=issue&itemId=50789625

**Comment by barbaburns** [comment]
No figma, os espaços entre heading h3 e texto estão fora de padrão, esta cada um num tamanho. Usei 40px como padrão.

**Comment by barbaburns** [comment]
as legendas precisam ser colocadas no bloco da imagem no admin

**Comment by barbaburns** [comment]
O iphone14 tem uma largura de tela maior que do figma. o comportamento padrão do texto é ocupar toda a area destinada ao texto, por isso não ocorre quebra de linha no titulo.

**Comment by daphnemartinsba** [comment]
retornos serão dados na issue #115
