### ISSUE TITLE
Bug em bloco de opinião na single de colunista

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#201]
No bloco opinião da single de colunista, ao passar o mouse por cima do título de algum post, o mesmo "some".

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/41d8e30c-a106-4617-bb3b-fb965cb899aa)

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/c54eaf71-05c0-430c-9c88-1675981c8d8f)

https://midianinja.org/author/andremenezes/

**Comment by Thayna-Zacharias** [comment]
![Image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/0bb0e351-20f3-4221-80dd-07180471e4fb)

Validado, aguardando visualização e aprovação do cliente para subir o ajuste em produção

**Comment by caio-ascava** [comment]
Foi realizado o teste e ao passar o mouse por cima de alguns títulos eles permanecem, ou seja, o bug foi corrigido.
