### ISSUE TITLE
Single de colunista com layout quebrado

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#202]
A página da colunista está com o layout quebrado com bloco relacionado a COP 26

https://midianinja.org/author/amandapellini/

![image](https://github.com/midianinja/ninja-wp-theme/assets/145383848/e63f0f88-4352-4194-a43f-566f0db74a81)

**Comment by caio-ascava** [comment]
Layout foi corrigido.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/6653d709-7aa6-49e6-901a-7547c007728d)
