### ISSUE TITLE
[FLICKR] ajustar embed do flickr conforme layout

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#22]

**Comment by estercmandrade** [comment]
@everaldomatias o bloco deve exibir a imagem da capa do álbum e ser direcionado para a url do álbum.

**Comment by daphnemartinsba** [comment]
O bloco é aplicado em acervo, na home, e na página de fotografia

**Comment by daphnemartinsba** [comment]
atualmente não estão inseridos os dados de localização em fotos/álbuns. É preciso inserir esses dados para que sejam exibidos.  Ações:
- inserir as informações nos álbuns anteriores
- iniciar a inserção dos dados geográficos nos álbuns/fotos futuras

**Comment by caio-ascava** [comment]
- [ ] Adequar tarja com localização e data, conforme figma

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/50f7902a-305f-4829-858a-666cbbb34c71)
