### ISSUE TITLE
Criar taxonomias de destaque para edição da home

### ISSUE THREAD

**Issue by laurahacklab** [midianinja/ninja-wp-theme#222]

**Comment by Thayna-Zacharias** [comment]
A taxonomia foi criada com o pods e foram criados também 3 opções de termos, "destaque 1" será o maior bloco, "destaque 2" o bloco à direita alinhado acima e o "destaque 3" é o bloco à direita alinhado mais abaixo.
Conforme as notícias são publicadas com a configuração de destaque 1, por exemplo, será considerada a mais recente para exibição no bloco.


![Image](https://github.com/user-attachments/assets/d069bdc0-bfd2-479b-be0b-cb56c01011c3)



![Image](https://github.com/user-attachments/assets/31d4fa6d-2444-4eaf-89e8-3c35e2ea370a)



![Image](https://github.com/user-attachments/assets/23572a81-bfce-4e68-8962-d843015eb2bf)




Ajuste disponível em dev para validação
