### ISSUE TITLE
ajuste de legenda em single de opinião

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#229]
legendas de imagens dentro de post de opinião estão com espaçamento grande. Após verificação com dev foi sugerido que o espaçamento fosse corrigido no código de modo que não afetará a single.
![image](https://github.com/user-attachments/assets/b143e395-c82d-424c-87e5-27eef0fdf170)

![image](https://github.com/user-attachments/assets/02b535dd-3e06-4aa5-832b-14bea79b97e9)
![image](https://github.com/user-attachments/assets/8766cdc1-723b-401a-a469-3b09ce38e0bc)
https://midianinja.org/opiniao/orquestra-sinfonica-jovem-faz-homenagem-a-compositora-negra-florence-price-no-theatro-municipal/

testes em local após ajuste:
![image](https://github.com/user-attachments/assets/02ebffa2-66c1-4f66-8cae-e841734dc2c6)

**Comment by Thayna-Zacharias** [comment]
![image](https://github.com/user-attachments/assets/d0d0e1a1-a4db-4bf5-8fea-5176cde55f98)

**Comment by Thayna-Zacharias** [comment]
ajuste disponível em dev para validação

**Comment by caio-ascava** [comment]
Validação concluída em dev.
