### ISSUE TITLE
[MOBILE] - Afluentes

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#232]
- [ ] Avaliar qual seria o comportamento esperado. Ou seja, o sublinhado azul deve ser quando passa o mouse (desktop) ou quando clica sobre cada alternativa (no mobile). No Figma, as opçoes estão sem linha azul (sublinhada)

![Image](https://github.com/user-attachments/assets/a09d8bac-536e-4300-9773-7b25aaa3215c)

**Comment by barbaburns** [comment]
Via de regra nenhum link tem sublinhado no projeto, então vou apenas tirar.
