### ISSUE TITLE
[SINGLE OPINIÃO] Ajuste em posts no rodapé

### ISSUE THREAD

**Issue by Thayna-Zacharias** [midianinja/ninja-wp-theme#240]
Solicitado pelo cliente que os posts exibidos no rodapé das singles de opinião sejam aleatórios, podendo ser os últimos publicados e que haja maior rotatividade dos autores exibidos.

![image](https://github.com/user-attachments/assets/2d9b00b6-521e-4697-9e09-178ad125e268)

**Comment by Thayna-Zacharias** [comment]
Ajuste foi feito de forma que na exibição de posts no rodapé ele exclui o post em exibição atualmente, também não repete posts, não repete o autor, e são de datas aleatórias, a cada vez que a single de opinião é atualizada.

**Comment by Thayna-Zacharias** [comment]
https://github.com/user-attachments/assets/7724331a-b6ed-4e94-a3d5-64d3c27ce504

**Comment by Thayna-Zacharias** [comment]
Ajuste disponível em dev para validação

**Comment by caio-ascava** [comment]
Validação concçuída após ajustes

**Comment by Thayna-Zacharias** [comment]
O código foi ajustado para que autores que não estão no coautors ( por exemplo 'colunista ninja' e 'ninja') não se repitam na exibição. 
Validação disponível em dev.

**Comment by caio-ascava** [comment]
validação concluída!
