### ISSUE TITLE
[LAYOUT] - Aplicar layout no bloco Últimos posts (Vertical)

### ISSUE THREAD

**Issue by everaldomatias** [midianinja/ninja-wp-theme#25]
Layout: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=0-1&mode=design&t=9wesr4Fzh6kyJbem-0

Aplicar o layout do bloco Últimos posts (Vertical), ele aparece 2 vezes na home (como ÚLTIMAS e COLUNAS). A diferença de conteúdo entre os blocos (como exibir ou não o título) são configurações do bloco e podem ser feitas pelo painel.

O bloco pode receber uma classe específica pelo painel, para diferenciá-los (como o background-color). Já os itens em comum (como espaçamentos e fontes) devem ser feitor de forma global, que alcancem quantos blocos existirem na página.

É preciso que o CSS contemple todas as configurações possíveis do bloco, por exemplo quando exibe ou não determinado dado.

O CSS deve ser feito no arquivo `_b-latest-vertical-posts.scss`.

**Comment by daphnemartinsba** [comment]
- [ ] Em colunas: limitar a dois colunistas por slide

Últimas Notícias

- [ ] Primeiro slide deve estar todo preenchido
- [ ] Metadado de data deve estar em português na versão português do site
- [ ] Cor do metadado deve mudar conforme cor da editoria
- [ ] Destacar uma editoria 
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/50cc9d54-f93f-4928-a5dd-f2c99c47f740)

**Comment by daphnemartinsba** [comment]
- [ ] Texto "Em" dos metadados não deve conter a cor dos metadados
figma:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/31ba7710-4f86-42f9-aa0e-8c72bb49750d)


dev:



![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/bb8013d7-51da-4472-86bb-459fdbd7bac5)

- [ ] Adequar setas do slide tanto de coluna quanto de ao layout do figma últimas
- Em últimas: seta o hover deve escureccer a seta


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/54149885-6d79-4216-a102-a3ae5f25170e)


- Em colunas o hover deve clarear


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/88143b2c-cf1a-44ee-9cb5-65d57a13bb7d)

**Comment by daphnemartinsba** [comment]
será resolvida na issue #38
