### ISSUE TITLE
[RODAPÉ]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#3]
Link do figma - desktop:
https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=562-355&mode=design&t=iYdVRgjdhhwlXRD7-0

Link do figma - mobile:
https://www.figma.com/file/fYtWSwozi6ROvFCMAGfM2y/Midia-Ninja-UI?type=design&node-id=562-1389&mode=design&t=iYdVRgjdhhwlXRD7-0

**Comment by daphnemartinsba** [comment]
- [ ] Tornar responsivo

**Comment by caio-ascava** [comment]
Figma
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/f6db0780-60d3-496b-aa53-eaf33a9d5436)
**Mobile** - (todos os modelos em todas as plataformas)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ef70b57e-0311-489c-a62b-b83380ef7ad2)

- [ ]  Ajustar ordem dos botões conforme Figma (Notícias, opinião, fotografia, afluentes, especiais, a mídia ninja, vídeo, loja e contato)
- [ ] Quando eu clico em qualquer uma das opções ele direciona para o topo da página (visualizado através de Iphone 15 pro max, Galaxy S23 e A10 (Safari, Chrome e Mozilla)).

**Comment by barbaburns** [comment]
Os links dos botoes serão implementados no final do projeto
