### ISSUE TITLE
[DESIGN TOKENS] Revisar e ajustar ao novo layout

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#30]
Styleguide: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-3&mode=design&t=I2vlWLtDC59ec7za-0
Componentes: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-2&mode=design&t=I2vlWLtDC59ec7za-0

O design token foi feito com base no antigo layout, portanto:

- [ ] Adequar o design token às especificações do novo layout disponíveis nos links acima

**Comment by daphnemartinsba** [comment]
- [ ] Aplicar tamanho, line height e weight no Título H5: Manrope 20 px 500 weight 30 px line height

**Comment by everaldomatias** [comment]
@daphnemartinsba aqui para essa issue estamos aguardando a atualização do brand tokens no figma, certo?

**Comment by daphnemartinsba** [comment]
> [@daphnemartinsba](https://github.com/daphnemartinsba) aqui para essa issue estamos aguardando a atualização do brand tokens no figma, certo?

Brand tokens Atualizado

**Comment by pivapedro** [comment]
@daphnemartinsba durante a conversa com o Pedro Lucas, identifiquei algumas inconsistências entre os tokens no Figma e o código atual. Seria importante mapear os impactos das alterações nos componentes já desenvolvidos, especialmente aqueles que estão utilizando os tokens atuais. Vide um exemplo:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/94075104/651bb88e-b428-49b5-897a-fcb4c59dd61d)

**Comment by daphnemartinsba** [comment]
> @daphnemartinsba durante a conversa com o Pedro Lucas, identifiquei algumas inconsistências entre os tokens no Figma e o código atual. Seria importante mapear os impactos das alterações nos componentes já desenvolvidos, especialmente aqueles que estão utilizando os tokens atuais. Vide um exemplo:
> 
> ![Image](https://private-user-images.githubusercontent.com/94075104/313333109-651bb88e-b428-49b5-897a-fcb4c59dd61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQxMjksIm5iZiI6MTcxMDc2MzgyOSwicGF0aCI6Ii85NDA3NTEwNC8zMTMzMzMxMDktNjUxYmI4OGUtYjQyOC00OWI1LTg5N2EtZmNiNGM1OWRkNjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjkxZDAzZTk5MzA2MTAwOTM1YTc3NGE0NjVlYTNhODFiNDlmOTFlZjgwYzJlOWRhMzJmODA0NzgwNGQxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLY2SLnRMuAUMgdJV38ATwqeAtyyFK-XHTUvBpRvSNE)

@pivapedro você poderia em primeiro momento mapear todas essas inconsistências? Teria alguma sugestão de como mapear esses impactos?

**Comment by pivapedro** [comment]
Segue os impactos mapeados:

# - Arquivos que necessitam de atenção

## - Cores sem variaveis

themes/midia-ninja-theme/assets/scss/6-pages/_p-single.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-page.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-page-anchor.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-home.scss
themes/midia-ninja-theme/assets/scss/5-blocks/_b-latest-vertical-posts.scss
themes/midia-ninja-theme/assets/scss/4-layout/_l-header.scss
themes/midia-ninja-theme/assets/scss/4-layout/_l-footer.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-share.scss
themes/midia-ninja-theme/assets/scss/3-components/\_c-list-terms.scss
themes/midia-ninja-theme/assets/scss/3-components/\_c-main-menu.scss
  ?? color: var(--Primary-dark, var(--DARK, #111)); line 55

## - Cores trocadas pelo caminho

assets/scss/1-settings/_s-variables.scss
--c-primary:  #{$c_blue_primary} ;

plugins/hacklab-blocks/assets/variables.scss
--c-primary: #{$c_red_primary};

$c_blue_primary: #035299;
--c-primary: #{$c_blue_primary};
assets/scss/3-components/_c-slider.scss

## - Cores e onde elas aparecem 

$c_blue_secondary: #B1D3E5;
themes/midia-ninja-theme/assets/scss/3-components/_c-slider.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-title.scss

--c-gray--darker: #{$c_gray_darker};
assets/scss/2-atoms/_a-typography.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-title.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-pagination.scss
themes/midia-ninja-theme/assets/scss/4-layout/_l-header.scss
themes/midia-ninja-theme/assets/scss/4-layout/_l-sidebar.scss
themes/midia-ninja-theme/assets/scss/5-blocks/_b-timeline.scss
themes/midia-ninja-theme/assets/scss/7-parts/_p-content-post.scss
themes/midia-ninja-theme/assets/scss/8-optional/_c-top-menu.scss

$c_primary
assets/scss/3-components/_c-button.scss
assets/scss/3-components/_c-carousel-posts.scss
assets/scss/3-components/_c-newsletter.scss
assets/scss/4-layout/_l-comments.scss



$c_gray__darker
assets/scss/3-components/_c-card.scss
 

$c_gray
assets/scss/3-components/\_c-carousel-posts.scss
assets/scss/3-components/\_c-follow-us.scss
assets/scss/3-components/\_c-forms.scss

--c-primary
themes/midia-ninja-theme/assets/scss/3-components/_c-main-menu.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-pagination.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-slider.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-title.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-wpml-language-menu.scss
themes/midia-ninja-theme/assets/scss/4-layout/_l-sidebar.scss
themes/midia-ninja-theme/assets/scss/5-blocks/_b-cover.scss
themes/midia-ninja-theme/assets/scss/5-blocks/_b-timeline.scss
themes/midia-ninja-theme/assets/scss/7-parts/_p-content-post.scss

$c_blue_primary
themes/midia-ninja-theme/assets/scss/3-components/_c-slider.scss
themes/midia-ninja-theme/assets/scss/3-components/_c-title.scss

--wp--preset--color**
plugins/hacklab-blocks/blocks/flickr-album-gallery/style.scss
plugins/hacklab-blocks/blocks/video-playlist/style.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-author.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-editor.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-home.scss
themes/midia-ninja-theme/assets/scss/6-pages/_p-tutorstarter.scss
themes/midia-ninja-theme/assets/scss/7-parts/_p-filter-posts.scss
themes/midia-ninja-theme/library/blocks/src/latest-horizontal-posts/style.scss

**Comment by daphnemartinsba** [comment]
blocked: aguardando aceite do PR

**Comment by daphnemartinsba** [comment]
- [ ] Alterar cor da fonte h1, h2, h3, h4 para #111111, no momento está #262626 
- [ ] alterar h2 para: 
font-size: 32px;
font-weight: 800;
line-height: 38.4px;
letter-spacing: -0.02em;
text-align: left;

na single de posts no staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/730d2997-17be-44a6-9f16-221a8545ac00)

- [ ] alterar h3 para:
font-size: 24px;
font-weight: 800;
line-height: 30px;
letter-spacing: -0.01em;
text-align: left;

na single de posts no staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/45a9502a-bdb8-4250-9fa6-16ed10295b6e)

- [ ] alterar h4 para:

font-size: 20px;
font-weight: 700;
line-height: 26px;
text-align: left;

na single de posts do staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d2ec88e4-72ab-4fb5-a4e6-78f4c8f141d5)

**Comment by daphnemartinsba** [comment]
retorno na issue #88
