### ISSUE TITLE
[RESULTADO DE BUSCA]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#33]
- [x] Criar estrutura da página
- [x] Aplicar estilo 
- [ ] implementar filtros e os blocos de videos, fotos, especiais

Figma: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=467%3A2589&mode=design&t=rsdwjNTlnThEVhUM-1

**Comment by daphnemartinsba** [comment]
Blocked: necessita auxílio para implementação nos filtros e os blocos de videos, fotos, especiais

**Comment by everaldomatias** [comment]
Aguardando revisão do layout após sugestões da equipe Ninja

**Comment by caio-ascava** [comment]
**Validação Desktop**
- [ ] 1. A thumb do lado direito está um pouco maior que thumb da esquerda
- [ ] 2. A fonte utilizada nos títulos devem ser:
**Figma** 
width: 370px;
height: 84.86px;
top: 571.62px;
left: 535px;
gap: 0px;
opacity: 0px;

A fontes das datas:
width: 370px;
height: 26.63px;
top: 1060.73px;
left: 535px;
gap: 0px;
opacity: 0px;

- [ ] 3. Padronizar espaçamentos entre campo de busca, filtro e ordenação. Padronizar também, os espaçamentos entre as thumbs, conforme figma.
- [ ] 4. Traduzir
- [ ] 5. As categorias estão sem as tags de cor
- [ ] 6. Algumas thums possuem bordas redondas e algumas ,quadradas.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/19331590-816d-40af-be32-3c8b47b24dce)

**Validação Mobile**

- [ ] Campos de buscas e filtros se apresentam no figma como lista suspensa.
- [ ] Padronizar tamanhos das thumbs
- [ ] Ajustar o titulo das thumbs em relação ao espaçamento após a thumb
- [ ] No figma as thumbs se apresentam uma por linha
- [ ] Ajustar as categorias nas thumbs que não possuem a tarja colorida
- [ ] Ajustar os icones de redes sociais e icone de instagram colado ao logo NINJA

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/37253a9d-5f13-48a2-9f1c-61c60b07f785)

**Comment by everaldomatias** [comment]
@filipesouzadev posso ajudar em algo aqui nessa issue?

**Comment by filipesouzadev** [comment]
> [@filipesouzadev](https://github.com/filipesouzadev) posso ajudar em algo aqui nessa issue?

fala eve! só vi agora. acho que ta tudo sob controle, o caio apontou ajustes pontuais aqui, nada muito complexo.
valeu demais! @everaldomatias

**Comment by filipesouzadev** [comment]
@caio-ascava você apontou ali como fonte questões de largura, altura, posicionamento:
width: 370px;
height: 84.86px;
top: 571.62px;
left: 535px;
gap: 0px;
opacity: 0px;

essas propriedades nem sempre vão estar refletidas por conta da responsividade da pagina. São propriedades estáticas.
qualquer coisa podemos conversar depois sobre isso e te explico melhor.
