### ISSUE TITLE
[HOME] Ajuste na cor no bloco de Últimas e de Colunas: seta do slider e string de data

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#38]
- [x] Texto "Em" dos metadados não deve conter a cor dos metadados
figma:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/31ba7710-4f86-42f9-aa0e-8c72bb49750d)

dev:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/bb8013d7-51da-4472-86bb-459fdbd7bac5)

- [x] Adequar **a cor** das setas do slide tanto de coluna quanto de ao layout do figma últimas
- Em últimas: seta o hover deve escureccer a seta

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/54149885-6d79-4216-a102-a3ae5f25170e)

- Em colunas o hover deve clarear

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/88143b2c-cf1a-44ee-9cb5-65d57a13bb7d)

**Comment by caio-ascava** [comment]
Ajuste na coloração do botão "**sem** hover" do mouse, porem deve manter o funcionamento do "hover".

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1f478425-f48e-4f3c-b11c-9bcffe169d39)
