### ISSUE TITLE
[SINGLE NOTÍCIAS] Resumo do coauthors

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#46]
- [x] Implementar resumo do coauthors:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/45196c65-7be9-49f6-94cb-dfe76ab57b5d)

Figma: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=269-3665&t=Z6HiZSvuzDgobCyW-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by thiagolamonte** [comment]
validação:

https://dev.midianinja.org/andar-com-fe-eu-vou-lavagem-do-bonfim-reune-fieis-ha-mais-de-270-anos/

**Comment by daphnemartinsba** [comment]
Testado no Samsung A10 e no Iphone Pro Max 14
- [ ] Redes sociais devem ficar abaixo do avatar e acima do separador
- [ ] No samsung: Cor do separador deve ser preta
- [ ] No layout, avatar consta com as bordas cortadas: investigar se é possível aderir
- [ ] No layout do mobile, a fonte da bio é 13px

Staging (samsung):
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/af510c43-d1ac-46c8-930d-2cc38ab516a5)

Layout:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/789a6928-c2b1-4173-be96-9f531a4e290a)

Desktop:

- [ ] alteração do layout: alterar fonte da bio para manrope 13px

**Comment by daphnemartinsba** [comment]
novo layout: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=2486-4634&t=NEqriy82glAqnVVE-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by thiagolamonte** [comment]
ajustes realizados de acordo com o layout novo do mobile

https://dev.midianinja.org/andar-com-fe-eu-vou-lavagem-do-bonfim-reune-fieis-ha-mais-de-270-anos/

**Comment by daphnemartinsba** [comment]
- [ ] alinhar tamanho do bloco com separador:
![image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/cae53208-4696-4a13-805a-6fdb602601bd)

**Comment by daphnemartinsba** [comment]
retorno na issue #75
