### ISSUE TITLE
[HOME] - Ajuste no bloco de mais lidas

### ISSUE THREAD

**Issue by everaldomatias** [midianinja/ninja-wp-theme#47]
Atualmente o bloco exibe o thumbnail, mas de acordo com o layout o bloco deve exibir o título e alguns metadados

**Comment by everaldomatias** [comment]
O bloco está funcional, precisa aplica as cores dos termos das categorias e a regra de negócio do bloco, para exibir efetivamente as notícias mais lidas, está em fase de definição.

**Comment by caio-ascava** [comment]
foram validados os pontos de aplicação de cores de categorias e verificado que o bloco está funcional, no entanto, não foi possivel avaliar a regra de negocio do bloco, que está em definição. Esta, foi incluída como nova Issue e será tratada atraves da Issue #54
