### ISSUE TITLE
[FONTE NINJA] Empacotar fonte

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#51]
Uma das fontes utilizadas é propriedade do NINJA. Vetorizar a fonte fará que o carregamento seja mais fácil:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/de599ac0-84ba-4775-b1ef-a54799bdef9d)

- [ ] Converter svgs em fonte utilizável

- [ ] Inserir no design tokens

**Comment by daphnemartinsba** [comment]
fonte precisa ser vetorizada

**Comment by daphnemartinsba** [comment]
blocked: aguardando retorno de resoluções da fonte

**Comment by marinarcruz** [comment]
Link dos arquivos no drive hacklab: https://drive.google.com/drive/folders/1KJ0yMVw6Svpgc0mqCO-310fX3GU9XpIn?usp=sharing

**Comment by daphnemartinsba** [comment]
para utilizar a fonte:
`font-feature-settings: 'calt' on;
font-family: "MidiaNinja";`
