### ISSUE TITLE
[MIGRAÇÃO] Publicações não identificadas.

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#53]
Ao migrar as publicações do CPT Post com a taxonomia Opinião, restaram 741 publicações.
Dessas 741 publicações, 207 estão identificadas com a categoria ENTREVISTAS, o restante são publicações NÃO IDENTIFICADAS.

Classificamos um cpt específico para essas publicações: NÃO CATEGORIZADO

- [x] Equipe Mídia Ninja vai classificar as publicações.

**Comment by marinarcruz** [comment]
28/03: É preciso inserir essa lista de publicações no arquivo de Arquitetura, para que eles possam fazer a classificação.

**Comment by marinarcruz** [comment]
20/05: acabamos identificando todas como OPINIÃO. Porém, ainda há posts de Notícias como Opinião e vice versa.
O maior problema é que há duplicações
