### ISSUE TITLE
[MAIS LIDAS] Implementar loop de útlimas notícias

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#54]
A regra de negócio do bloco, para exibir efetivamente as notícias mais lidas do dia, está em fase de definição.

**Comment by julialaurentino** [comment]
- [ ] Os títulos estão em caixa alta, deixar no formato regular (maiúsculas e minúsculas)

**Comment by daphnemartinsba** [comment]
- A regra foi aplicada em blocos, na archive de notícias/editorias não são blocos, é direto no código
- A contagem da visualização exclui visualização de admin
funcionamento:

https://github.com/midianinja/ninja-wp-theme/assets/75261677/dabf0bbe-c514-4c2e-a867-db890f7ea3ab
