### ISSUE TITLE
[CABEÇALHO] Correções pontuais

### ISSUE THREAD

**Issue by caio-ascava** [midianinja/ninja-wp-theme#55]

**Comment by caio-ascava** [comment]
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/61bf0038-b571-49b1-b8a1-173b69e523c4)

- [ ] desktop resolução 1366 e 1920: ao rolar a página para baixo o cabeçalho aberto pelo hamburguer para de ocupar o comprimento vertical completo da tela

- [ ] desktop resolução 1366 e 1920: centralizar follow our social media e seus ícones, e diminuir a distância entre o separador e o texto, após a loja (possível observar na imagem acima, ícones e texto descentralizados.

- [ ] desktop: ajustar conteúdo textual do campo de busca ("você" está abreviado como "vc")

- [ ] desktop: ao abrir a seção, a borda do topo da tabela deve permanecer com a cor e a borda, ficando mais evidente que os demais traços da tabela

- [ ] desktop: resolução 1366 e 1920: aumentar espaço entre lupa e espaçamento do hamburguer: aproximadamente dobrar distância atual
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0b705872-8e30-4aad-9562-cdf0830644b7)

**Comment by caio-ascava** [comment]
- [  ] Ao rolar a tela para baixo, o cabeçalho fica piscando;
- [  ] Pouco antes de mudar de estilo já é o inicio de corte do cabeçalho/imagem;
- [  ] Após esta transição, o logo fica cortado e o cabeçalho permanece reduzido


https://github.com/midianinja/ninja-wp-theme/assets/151761173/e466af8f-e131-46b2-b6d6-0a56f1794147

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0ee4e67d-c3a8-4dc3-88d6-cc20e379aa68)

**Comment by barbaburns** [comment]
@caio-ascava o cabeçalho/logo aparece cortado por conta da barra de admin do wp. se vc não estiver logado vai estar correto.

**Comment by daphnemartinsba** [comment]
Layout atualizado: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=2667%3A4793&mode=design&t=FNgd9dnnhEa4JwIc-1

**Comment by barbaburns** [comment]
nao consegui identificar o motivo no cabeçalho ficar piscando quando diminui. vou investigar isso com o @everaldomatias

**Comment by caio-ascava** [comment]
O cabeçalho voltou a piscar... fiz os testes pelo Edge, Mozila e Chrome... Pelo Chrome piscou em todos os testes e até pelo browser stack.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/7a32c46a-e776-431e-b9e8-a1b8f976aab4)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b9145240-eeb9-47ba-9a21-1d4404096a12)

o que eu identifiquei é que ele pisca agora, qdo vc rola a tela de baixo pra cima... faz assim, vai bem devagar rolando o mouse p baixo... daí vai subindo bem devagar tb... depois vc pega desde ali de cima, da umas duas ou 3 roladas p baixo.. e sobe de novo bem lentamente, uma roladinha por vez (qdo ele faz tipo um click)

**Comment by caio-ascava** [comment]
- [ ] Retirar a linha preta que limita o cabeçalho.
- [ ] Nos testes com mobile (android e IOS) o cabeçalho ao rolar a página para baixo não reduz de tamanho.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b7420642-4262-4c54-9cbc-9b83d78cfc02)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/03ffbf2c-585c-41fe-b777-82f636f9d8df)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b068a8c3-06a7-4736-9ea3-da0dbb01d7d4)

**Comment by caio-ascava** [comment]
- [ ] O cabeçalho, tanto em desktop quanto nos testes Mobile apresenta um tamanho superior ao Figma. 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ebd7cd06-3c0e-4113-808b-980fe006d7c1)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c0dd631d-d6ac-40ef-8f84-0b28bfe5d13d)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/a620a399-cad4-4ce6-81cd-d712f73b8749)

**Comment by daphnemartinsba** [comment]
retornos e alterações de layout na [#85](https://github.com/midianinja/ninja-wp-theme/issues/85)
