### ISSUE TITLE
[HOME] Ajuste no bloco de editorias

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#57]
- [x] Exibir categorias após filtragem
- [x] Inserir opção limpar filtro

**Comment by everaldomatias** [comment]
@daphnemartinsba ajustes aplicados. Para validar, o bloco já está no dev.

**Comment by daphnemartinsba** [comment]
Ao marcar uma subcategoria, é necessário marcar a categoria parent para que apareça no filtro do bloco
