### ISSUE TITLE
[AFLUENTES] CINE NINJA

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#58]
- [x] Criar estrutura da página
- [x] Aplicar layout na página
Figma: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-11540&t=Ss89WERZVwwJJZVo-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by daphnemartinsba** [comment]
* CINENINJA: 
        * no bloco CINE NINJA INDICA: publicações com o marcador CINE NINJA INDICA
        * Estreias da semana: será um quadro, eles provavelmente não existem ainda, enquanto ainda não tiver o marcador certo, deixa do afluente
            - ester vai tentar criar os termos pra já deixar puxado
        * Premiações: vai ser tag

**Comment by everaldomatias** [comment]
@daphnemartinsba movendo issue para validação do CineNinja

**Comment by caio-ascava** [comment]
- [ ] 1. Colocar a linha   abaixo de CineNINJA
- [ ] 2. Ajustar tamanho do bloco, alinhado ao   bloco CineNinja
- [ ] 3. Aproximar os ícones das redes sociais   e jaustar ordem
- [ ] 4. Ajustar tamanho do bloco de texto,   conforme FIGMA
- [ ] 5. Achei a imagem e texto do bloco   Critica bem embaçadas para leitura na resolução 1366x768
- [ ] 6. No figma as datas no bloco ESTREIAS DA SEMANA estão em cinza claro, mas em staging aparecem de coloração azul.
- [ ] 7. as duas imagens do lado direito estão com tamanhos iguais porem ultrapassando a margem (note que parecem estar uma linha abaixo das imagens da esquerda. (pode ser que seja pelo tamanho do título)
- [ ] 8. Também é necessário ajustar o tamanho da caixa de texto dentro do bloco, pois no Figma apresenta-se menor. (note que, a frase quase chega a margem do bloco, porem no figma há um espaçamento maior.)
- [ ] 9. Não está aparecendo o responsável "Por Cine Ninja" no bloco Cine ninja indica
- [ ] 10. Precisa também reduzir o campo de texto do titulo CINE NINJA INDICA

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0b7dce6c-38e8-4403-ae92-c861c553fc44)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/0700f16b-03cc-4025-8737-135e3d40c6e0)

**Comment by caio-ascava** [comment]
Esta issue está sendo encerrada pois foi criada a #145 [AFLUENTES] Cine Ninja - Pendências complementares, com as pendências vistas nas revalidações destas ações.
