### ISSUE TITLE
[ARCHIVE AFLUENTES]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#59]
Link figma desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=783-3159&t=a2Lduy0lVl7ZTg6t-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Link figma mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=783-3275&t=a2Lduy0lVl7ZTg6t-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by dioliviers** [comment]
Falta 
Fazer o bloco de coluna vertical que mostra a editoria exibir a editoria correspondente a Afluentes ( iremos desenvolver de todas editorias, pelo que entendi na semanal )
Alterar o mecanismo de busca padrão que está em afluentes para exibir na mesma pagina a palavra chave com relação aos afluentes ( Vou precisar de um help ).

**Comment by dioliviers** [comment]
OBS: Está aparecendo 'HACKLAB' porque os posts do CPT afluentes não está com o resumo preenchido.

**Comment by caio-ascava** [comment]
- [ ] Inserir imagem de fundo e imagem embaçada.
- [ ] Diminuir fonte
- [ ] Colocar AFLUENTES em caixa alta
- [ ] Adequar o tamanho dos cards dentro do bloco escuro.
- [ ] Alinhar campo de busca
- [ ] Inverter cor das setas e inserir os pontos entre elas em tom degradê

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/26b2a0d7-6c44-4602-9a8b-5048c36c5d6b)

**Comment by daphnemartinsba** [comment]
ajustes finos retornados na issue #118
