### ISSUE TITLE
[HOME] Criar novo bloco de destaque da home

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#6]
- Novo bloco deve substituir o atual

- [x] Desktop
- [x] Mobile

Layout: https://www.figma.com/design/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?node-id=7036-8557&t=H95gq3sJJrfDmQtc-0

**Comment by daphnemartinsba** [comment]
blocked: aguardando definição, se fará parte de um modelo específico ou se será somente bloco

**Comment by thiagolamonte** [comment]
https://dev.midia.ninja/
