### ISSUE TITLE
[HOME] ÚLTIMAS e COLUNAS - ajustar estilo e conteúdo dos metadados

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#61]
**ÚLTIMAS**

- [x] Data: ajustar quebra de linha
- [x] Metadado da editoria: manter a mesma fonte do metadado com a cor específica da editoria
ninja_background_term_color
ninja_font_term_color

Figma:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/ce5ec715-e1c2-4b44-ab94-e92486974771)

dev:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/7c7ed95c-a126-496c-a934-ba9d7ec87a8e)

**COLUNAS**

- [x] Deve conter como Título o  titulo da coluna 
- [x] deve conter como subtítulo o nome do autor

dev:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/3d93e984-bc00-49e4-8e12-8b2d9c439aa4)

Figma: 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/03a80214-cf41-4f97-8e98-8b0b14b419c8)

**Comment by barbaburns** [comment]
O layout do figma deve considerar o tamanho do formato da data. atualmente considera apenas a linha "a 53min" mas na verdade muitos post terão o formato maior de data. Neste caso precisa definir qual o melhor formato para essa data.

**Comment by daphnemartinsba** [comment]
@barbaburns conversei com o Pedro e deixa a data no formato dd/mm/aaaa

**Comment by barbaburns** [comment]
@everaldomatias  vai resolver a questão do conteudo das colunas

**Comment by barbaburns** [comment]
como a cor de cada editoria agora é selecionada pelo painel, preciso ver com @everaldomatias se é possivel pegar essa informação para aplicar na folha de estilo.

**Comment by daphnemartinsba** [comment]
retorno será resolvido na issue #99
