### ISSUE TITLE
[ALERTAS] Estilizar alertas do site

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#62]
- [x] fale conosco
  - Estilizar alerta de envio: o modelo do alerta deve ter a borda amarela, da mesma cor do botão enviar
  - Estilizar spinner
- [x] seja ninja
  - Inserir alerta de envio
- [ ] newsletter

Utilizar modelo:
https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-6300&mode=design&t=8fC23hDy7Mmknfe0-0

**Comment by caio-ascava** [comment]
Após o preenchimento dos dados e envio do formulário em ambas as telas, ocorreu um erro.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/30fc7ad7-cb6a-416e-9960-29a916cbe11d)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/909f952c-014b-4366-bfc5-c801665d2adc)
