### ISSUE TITLE
[FALE CONOSCO] Ajustes gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#63]
**Desktop**

- [x] Adequar layout à resolução 1366
       - caso sua tela não suporte a resolução 1366, utilizar a responsividade do inspecionar

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d4f29e1b-8f09-444b-8c63-56f05640ed5a)

- [x]  Formulário: aplicar borda de 1px #E2E2E2
- [x] Formulário: alterar fonte de dentro do formulário para DM Sans 14px line height 24px e weight 400
- [x] Formulário: botão deve estar com enviar em caixa alta 
- [x] Formulário: travar tamanho do campo de mensagem

- [x] newsletter:  alterar fundo para #262626
- [x] newsletter:  adequar conteúdo do texto ao do figma

**Mobile** Iphone 14 pro max Samsung S23

- [x] Iphone (safari) e Samsung (firefox): Ajustar embaçado no header

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/22307e67-9d76-4543-a7bf-ecf85895fe37)

- [x] Iphone e Samsung: ocultar anúncio após botão enviar
- [x] Diminuir espaçamento entre ícones das redes

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/9fa3f72d-27fc-4cfc-8ed4-bd91be69bf98)

- [x] Samsung (firefox): retirar sombra dos campos

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d3e27739-9001-4553-a17e-33a0a2a61756)

Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=467-2356&t=BxZsn8s8JUABO9xT-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=467-2592&t=BxZsn8s8JUABO9xT-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by filipesouzadev** [comment]
@daphnemartinsba sobre o item: Formulário: alterar fonte de dentro do formulário para DM Sans 14px line height 24px e weight 400
a fonte já estava aplicada, você pode validar no computed da página. acredito que ela não está declarada ainda no projeto e por isso fica em times news.

**Comment by filipesouzadev** [comment]
@daphnemartinsba resolução local em 1366px



![Image](https://github.com/midianinja/ninja-wp-theme/assets/52901592/aa1d6730-0793-41e1-929f-8ce5e416219b)

**Comment by caio-ascava** [comment]
- [ ] Alterar Size para 13px

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/744f4dc8-f409-4ca0-9a50-0764ade1ce21)

- [ ] Fale conosco tem line height tem 55.2px no Figma

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/5f7c9752-5cb1-4b90-a892-72f7c90d6c0d)

- [ ] Este texto no Figma possui line height de 18.85px

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ad99800e-0252-44f2-8ace-60975726a811)

- [ ] Esta frase no Figma possui line height de 18.85px

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/5cce2cbe-f41a-42f5-9fea-b50baf25f192)

**Comment by daphnemartinsba** [comment]
- [ ] resolução 1920 e 1366 alinhar blocos:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/96ed6fe2-7b61-42ba-b934-254f910619ef)

- [ ] 1920: Diminuir distância entre os dois blocos acima

**Comment by daphnemartinsba** [comment]
retornos na #84
