### ISSUE TITLE
[404]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#65]
Figma desktop:
https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1924-4248&t=9NbhtsHSsffsXUfP-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Figma mobile: 
https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1924-4205&t=9NbhtsHSsffsXUfP-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- [x] aplicar gif

**Comment by caio-ascava** [comment]
Foi identificado que o Gif foi aplicado, no entanto, ele está descendo um pouco mais do que deveria.

- [ ] Ajustar Gif dando a impressão de que ele fica sobre o botão "voltar para Home" e não descendo por trás deste botão.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/27ea91e1-36bc-4444-a224-e6f63c024f76)

**Comment by dioliviers** [comment]
ajustado

**Comment by daphnemartinsba** [comment]
retorno na #76
