### ISSUE TITLE
[RESULTADO DE BUSCA] NENHUM RESULTADO

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#66]
Layout figma: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1924-4788&t=9NbhtsHSsffsXUfP-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Layout mobile:
https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1924-5272&t=9NbhtsHSsffsXUfP-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- [ ] Bloqueada enquanto a resultado de buscas não é realizada

**Comment by daphnemartinsba** [comment]
blocked: aguardando issue #33

**Comment by caio-ascava** [comment]
- [ ] 1. A thumb do lado direito está um pouco maior que thumb da esquerda
- [ ] 2. A fonte utilizada nos títulos devem ser:
**Figma** 
width: 370px;
height: 84.86px;
top: 571.62px;
left: 535px;
gap: 0px;
opacity: 0px;

A fontes das datas:
width: 370px;
height: 26.63px;
top: 1060.73px;
left: 535px;
gap: 0px;
opacity: 0px;

- [ ] 3. Padronizar espaçamentos entre campo de busca, filtro e ordenação.
- [ ] 4. Traduzir
- [ ] 5. As categorias estão sem as tags de cor
- [ ] 6. Algumas thums possuem bordas redondas e algumas ,quadradas.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/19331590-816d-40af-be32-3c8b47b24dce)

**Comment by filipesouzadev** [comment]
@caio-ascava beleza? acho que aqui vc validou a search-result completa. no caso essa issue é pra quando não há nenhum resultado encontrado. você pode validar pesquisando uma palavra que não existe.

**Comment by caio-ascava** [comment]
- [ ] 1. Aplicar espaçamento no título e campo de busca;
- [ ] 1. Utilizar fonte conforme FIGMA:
                font-family: Manrope;
                font-size: 48px;
                font-weight: 800;
                line-height: 55.2px;
                letter-spacing: -0.03em;
                text-align: left;
- [ ] 2. Traduzir a string pelo WPML
- [ ] 3. Utilizar fonte para a quantidade de resultados encontrados:
                font-family: Manrope;
                font-size: 20px;
                font-weight: 700;
                line-height: 26px;
                text-align: left;

- [ ] 4. O tamanho do retângulo do campo de buscas no figma é:
               width: 460px;
               height: 46px;
               top: 260px;
               left: 137px;
               gap: 0px;
               border-radius: 8px 0px 0px 0px;
               border: 2px 0px 0px 0px;
               opacity: 0px;


![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/59f37dea-b8bf-4d30-a8b5-ca132eeda1fb)

**Comment by caio-ascava** [comment]
Dentro desta issue tem uma ação pendente há alguns dias, porem como está em fase de validação, estou criando uma nova issue para ajuste desta ação:

- [ ] Traduzir a string pelo WPML
