### ISSUE TITLE
[SINGLE NOTÍCIAS] layout mobile e publicações com posts e vídeos

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#68]
layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=2486-4634&t=gPAyArdC9YfCM4J6-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

layout atualizado: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=269-3665&t=gPAyArdC9YfCM4J6-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- [x] Imagens devem constar com resolução do layout: setar dimensão de layout nas opções do bloco de imagem, para imagem vertical (alinhada com o texto) e para imagem horizontal

- [x] Aplicar o layout do mobile

- [x] Readequar ao layout versão desktop tb

- Em análise: duplicação de imagem de destaque e resumo no corpo do texto

- Manter as proporções dos elementos pixel perfect, tanto no mobile, quanto na resolução 1920 e 1366

**Comment by daphnemartinsba** [comment]
- [ ] Ao utilizar nenhum, na largura da imagem, a imagem fica com o padrão vertical. Aplicar padrão horizontal para a largura ampla
- [ ] Internacionalizar as strings: varrer pelo WPML e traduzir para português
- [ ] Tratar imagens de leia mais para melhorar resolução, algumas parecem que estão esticadas:
staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e2504216-282f-4d89-aa58-dc80fba4f7ce)


- [ ] Alinhar tamanho e posição da imagem de destaque, a posição do título e do resumo ao resto do conteúdo do texto
    - [ ] Alinhar separador à imagem de destaque:
figma:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/28788f73-9f07-4fb6-8a75-bebe111c9cbc)


staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/24002c17-0a1c-4fcb-9726-19bc52775475)


    - [ ] Alinhar título e resumo à extensão do separador na direita, e alinhar ambos na esquerda, conforme figma:
figma:
 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d7ea9de4-1386-4125-b6f5-363c145bc1dc)

Staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/68091043-dd2f-4c31-bb60-5eb5d7492757)


    - [ ] alinhar autor ao destaque, título, resumo e separador:
staging:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/bd2a3030-5014-4c38-8577-01c7d24fd423)


- [ ] Ajustar redes sociais ao lado do autor:
    - está extrapolando o separador à direita, deve estar alinhado
    - deixar mais para cima, alinhar topo com metade do nome do autor, e bottom com início do horário
    - Aumentar ícone
- [ ] aumentar ícones de redes sociais no pé da página
- [ ] **CONFIRMAR:** Aplicar na legenda da foto: 
    - font-family: Manrope;
    - font-size: 14px;
    - font-weight: 500;
    - line-height: 21px;
    - letter-spacing: -0.03em;
    - text-align: left;
    - cor: #848484
- [ ] Na fonte do parágrafo alterar line height para 140% aplicar weight 500
- [ ] No título dentro do conteúdo do post, alterar line height para 130% e weight para 800   
- [ ] Em Leia também alterar line height para 120%
- [ ] Retirar sublinhado do título das postagens de leia também
- [ ] Aplicar hierarquia das classes orientada na reunião semanal 
- [ ] Etiqueta da editoria deve pegar a cor da fonte e do fundo da imagem de destaque e na thumb de leia também
- [ ] Mobile Iphone 14 Max Pro: aplicar bold em Compartilhe e alinhar conforme figma
- [ ] Mobile Iphone e Samsung: ajustar alinhamento do avatar do autor em referência ao nome e à data da postagem
- [ ] Mobile Iphone e Samsung: alinhar título leia também com thumbs
- [ ] Mobile Iphone e Samsung: aumentar e centralizar tamanho da thumb:

Staging:
![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/7cb43bb0-7a33-4d57-9a71-59c21d190be6)

Figma: 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/e1bcb228-cf7a-4237-965b-d18d9a7ef5c8)

**Comment by barbaburns** [comment]
Os icones das redes sociais estao com 24px conforme o figma, mas no figma os icones em si não estao com o mesmo padding.

**Comment by caio-ascava** [comment]
- [ ] Avaliar formatação do bloco azul à direita;
- [ ] Avaliar se serão 3 noticias ou duas, ou se ocorre devido a ter apenas 02 relacionadas a alimentação.
- [ ] Achei as letras embaçadas junto ao bloco cinza.
- [ ] Poucas categorias possuem a informação adequada. Sendo que a de cultura foi a melhor avaliada.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/86418e65-16f2-460f-8303-2a73eea586b1)

Alguns exemplos, não se limitando a:

**Alimentação** https://novo.midianinja.org/category/alimentacao/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/3daa2ca0-e06a-4ac0-a265-c0e9f126797c)

**Agricultura-familiar** https://novo.midianinja.org/category/agricultura-familiar/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/caa1a976-e8c1-459c-9d73-ebc2ce5a0b94)

**Agronegócio** https://novo.midianinja.org/category/agronegocio/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/9122f08d-b8e3-4779-b3dc-6c78d3947df6)

**Agrotóxicos**: https://novo.midianinja.org/category/agrotoxicos/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e1f09e5b-8697-46e4-b6fc-8e641ba5a084)

**Fome**: https://novo.midianinja.org/category/fome/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/832defb2-8cd4-46ea-9fa3-a9e827988f39)
(visualmente, via mobile, única categoria que teve alteração entre IOS e android) - FOME
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ebd0aa22-9015-4c9b-8cb2-7574a9b0a9f7)

**Inovação** https://novo.midianinja.org/category/inovacao/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e80a008b-5b34-4f7c-aec8-d2a2601b8d07)

**Maconha medicinal** https://novo.midianinja.org/category/maconha-medicinal/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/aff8fa7f-cca7-4f9b-a83e-3d37ee884f61)

**IPHONE 14 PRO e S23**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/418800af-8ea2-441d-8f5e-0a6b46daade9)

**Comment by daphnemartinsba** [comment]
- [ ] legenda da imagem de destaque não aparece

**Comment by daphnemartinsba** [comment]
seguindo fluxo do QA, retornos serão dados na issue [#105](https://github.com/midianinja/ninja-wp-theme/issues/105)
