### ISSUE TITLE
[ARCHIVE OPINIÃO]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#7]
Layout: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=103-847&t=KNAabUyyx1qxX9sx-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- Archive do CPT Opinião
- [x] Criar Estrutura
- [x] Aplicar Layout
- [x] Deixar responsivo

**Comment by barbaburns** [comment]
O bloco Mais lidas tem meta-info diferente entre mobile e desk. Assumi o meta-info de desk (data - por author).

**Comment by daphnemartinsba** [comment]
blocked: staging foi atualizado, mas ainda está diferente do dev e do local

**Comment by daphnemartinsba** [comment]
**Desktop 1920 e 1366**
- [ ] No destaque, alterar fonte do título da notícia listada à direita, alterar fonte para 20px com line height em 26px e 600 eight:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/8ec41c5c-5485-4a2d-9113-0d680b4a9eff)


- [ ] No destaque, alterar fonte para 13 px com line height 18.85 e weight 700:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/376fec53-bf17-4474-b449-7f86237b5b5f)



- [ ] Lista de reportagens por colunistas deve ter o nome do autor em caixa alta


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/4c575355-63df-4030-9774-c7758d44955f)


- [ ] Bloco de mais lidas deve ficar alinhado com o topo da primeira linha de notícias e se extender até o meio do componente de paginação
   -  [ ] deve listar 4 notícias
- [ ] Paginação da lista de notícias: utilizar ícone '>' do figma e centralizar 
- [ ] Anúncio deve alinhar com o título Conheça os colunistas NINJA
- [ ] Alterar fonte do botão Todos os colunistas: cor da fonte deve ser F5F5F5, 14 px e 21 de line hegiht cor de fundo do botão deve ser #111111
- [ ] adicionar código da newsletter: [mc4wp_form id=4539338]
- [ ] listar colunistas no bloco todos os colunistas
- [ ] Internacionalizar strings no text domain 'ninja'

**Mobile:**
- [ ] Inserir slider do bloco de colunistas do destaque
- [ ] retirar paginação e adicionar botão Ler mais opiniões abaixo de separador (adicionar separador)
- [ ] ativar slide de conheça os colunistas a partir de mais de dois colunistas

**Comment by daphnemartinsba** [comment]
- newsletter será padronizada para todas as páginas, aplicada no rodapé

**Comment by daphnemartinsba** [comment]
- [ ] alterar fonte que está cinza, deixar conforme figma:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/6329e2fb-2d05-43c6-b5c2-482ce2c18513)
