### ISSUE TITLE
[SINGLE OPINIÃO]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#70]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=862-3712&t=9nPg6SO4Q4Q1plLD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=862-4068&t=9nPg6SO4Q4Q1plLD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by caio-ascava** [comment]
Mobile (Iphone 14 Pro):
- [ ] Ajustar Título e bloco mais próximo ao cabeçalho.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/db0cd35d-c9ac-49c6-85a7-3cf9b08c494f)

Desktop
Bloco a direita precisa ajustar o circulo da foto para dentro do retângulo
Inserir o nome do colunista abaixo da foto
Incluir ícone do Instagram ao final do texto
Centralizar título, comparado a linha de data e resumo do texto.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/dda753ce-822f-4b46-a115-3aa3915f1890)

Diminuir weight para 700

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/afb5121a-8f94-464c-8827-16e91c9b5809)

**Comment by dioliviers** [comment]
-> Peso da fonte para 700 weight OK 
-> Inserido titulo abaixo do avatar OK 

Mobile: Retirado o 'respiro' entre o cabeçalho e o conteúdo :


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/b44a0cef-93e0-4b3c-a314-79e967d42d0f)


Observações: Está sem avatar porque o usuário não inserio imagem no usuário dele, sem redes sociais pelo mesmo motivo, porém se ele insere 2 e a terceira ele não preenche só irão aparecer as redes sociais ATIVAS, as não preenchidas não são exibidas.

**Comment by caio-ascava** [comment]
- [ ] Na resolução 1366x768, o resumo do texto aparece em uma única linha e o bloco escuro com o perfil não aparece.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/bb0bdba8-a572-4e4e-b1d4-564705521195)

**Comment by dioliviers** [comment]
OBS: tem bastante card que o perfil não está preenchido por completo, sendo assim as informações não aparecem, é necessário 'garimpar' até achar um perfil com todas as informações completas.

**Comment by caio-ascava** [comment]
@dioliviers Verifiquei os pontos ajustados e estão ok, no entanto, identifiquei no texto um certa falta de padronização nas frases.

https://novo.midianinja.org/opiniao/como-descobri-que-poderia-morrer-sozinha/

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/2985e0ca-a89a-473a-8751-9a7fc9baac01)

Pelo iphone 14 pro, é possível identificar que os ícones das redes sociais precisam estar mais próximos.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ab646d1c-400b-4b3c-963b-3e35789200ad)

**Comment by daphnemartinsba** [comment]
retorno na #97
