### ISSUE TITLE
[ARCHIVE ESPECIAIS] 

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#71]
layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=782-1964&t=9nPg6SO4Q4Q1plLD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=782-2194&t=9nPg6SO4Q4Q1plLD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by caio-ascava** [comment]
**MOBILE e DESKTOP**
- [ ] - [ ] Alinhar as imagens ao ícone de Instagram do cabeçalho e a lupa de busca.
- [ ] No bloco escuro à direita falta incluir o título "ESPECIAIS"
- [ ] Neste bloco, as setas devem ser Esquerda (cinza claro) e direita (branca).. Os pontinhos devem começar cinza claro e ir escurecendo para a direita.
- [ ] As imagens acima destas setas, devem ser menores e mais largas. E a próxima imagem deve estar mais á esquerda, com um espaço escuro antes da borda do bloco.
- [ ] Seus títulos também devem estar alinhados à margem esquerda de cada imagem
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1d6f91d2-6a81-4361-8880-a377ef0ab01d)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/511d17b4-9b88-49db-8faf-4d6afd3bc23f)


- [ ] Adequar a imagem que possui leve transparência na metade do bloco.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/52bd7104-ed48-4966-acf5-2592ddccc187)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/7d1020d5-d480-4e44-8b6d-a2affd037365)

**Comment by caio-ascava** [comment]
Desktop - resoluções de 1366x768 e 190x1080
- [ ] 1. Aumentar tamanho de fonte
- [ ] 2. Reduzir espaçamento de "ESPECIAIS"
- [ ] 3. Alinhar os 3 parágrafos
- [ ] 4.Inserir título "Especiais" dentro do card
- [ ] 5. Diminuir tamanho das figuras dentro do bloco, sendo necessário que a próxima imagem seja melhor posicionado e com leve sombreado à direita.
- [ ] 5. Formatar os títulos dos cards 
- [ ] 6. inserir os pontinhos em degradê
- [ ] 7. Alinhar os espaçamentos entre o campo buscas e Edital Doritos
- [ ] 7. Ajustar ícone Lupa no campo de buscas
- [ ] 8. Ajustar tamanhos dos cards e colocar títulos em negrito
- [ ] 9. Alinhar os blocos

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/7ae07a4f-59ea-4c06-897c-83ccdbd42dec)

**Comment by caio-ascava** [comment]
MOBILE - S23 e Iphone14 Pro

- [ ] 1. Colocar título em caixa alta e aumentar tamanho de fonte
- [ ] 2. Colocar título em caixa alta e aumentar tamanho de fonte
- [ ] 3. Ajustar distanciamento entre blocos que possuem imagens sobrepostas
- [ ] 4. Atrás desta imagem que está sobreposta, no figma o espaçamento entre os blocos é o mesmo
- [ ] 4. a imagem do edital doritos respeita o enquadramento, mas nos testes mobile ela passa as margens.
- [ ] 4. Os cards tambem estão alinhados aos blocos superiores
- [ ] 5. Ajustar tamanho dos cards e distanciamento entre eles, conforme Figma

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e4421e0b-34f6-41af-9526-475d8834ba24)

**Comment by daphnemartinsba** [comment]
- [ ] Alteração de layout: suprimir blocos de especiais da primeira dobra e expandir o bloco de destaque do acervo ninja

**Comment by daphnemartinsba** [comment]
retornos na #108
