### ISSUE TITLE
[SINGLE DO COLUNISTA]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#72]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-11158&t=9nPg6SO4Q4Q1plLD-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- Single do co-authors:
https://codex.wordpress.org/Author_Templates

**Comment by dioliviers** [comment]
Aguardando finalizar a migração para atualizar o tema e entregar a tarefa

**Comment by dioliviers** [comment]
OBS: SLUG recebemos a orientação pelo Bruno para deixar em off por enquanto.

**Comment by daphnemartinsba** [comment]
- [ ] Inserir botão para ver todos os colunistas
- [ ] Alinhar grid das notícias à esquerda, reparar no layout, em 1920 e 1366


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/b9a80e47-149f-4664-a99c-d45e0918cc14)

- [ ]

**Comment by dioliviers** [comment]
OBS: o grid no mobile no layout é bem coladinho mesmo, dei um " respiro no grid " pra melhorar a visualização, fora isso, fiz os ajustes de margin e etc

**Comment by caio-ascava** [comment]
Esta issue está sendo encerrada pois foi criada a Issue #147 [[SINGLE DO COLUNISTA] - ajustes pendentes e complementares
