### ISSUE TITLE
[PÁGINA COLUNISTAS]

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#73]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=852-2422&t=8fC23hDy7Mmknfe0-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=938-3373&t=8fC23hDy7Mmknfe0-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by daphnemartinsba** [comment]
blocked: aguardando ajustes de finalização da migração

**Comment by daphnemartinsba** [comment]
- [ ] implementar paginação da coluna Mais colunistas NINJA
- [ ] arredondar borda do destaque principal conforme figma
- [ ] Bloco mais lidas: bloco muda de tamanho conforme tamanho conteúdo das postagens no slider variam
- [ ] Mobile: Bloco mais lidos ta sem slider no mobile
- [ ] Mobile: revisar/ajustar largura dos blocos conforme layout do figma
- [ ] Mobile: diminuir distância entre bloco mais lidos e colunistas
- [ ] Mobile: aumentar espaço entre bloco mais lidos e avatar
- [ ] Mobile: diminuir para 4 colunistas na lista do meio da página, que tem os resumos
- [ ] Mobile: mostrar avatar do bloco mais colunistas ninja em duas colunas e 6 linhas

**Comment by caio-ascava** [comment]
- [ ] Ajustar fonte da data 

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c9c3afc6-78ab-4e3c-be0a-14139be43cdd)

**Comment by dioliviers** [comment]
efetuado revisão na pagina de colunistas e parece que está batendo com layout : 


![Image](https://github.com/midianinja/ninja-wp-theme/assets/7771249/d61781d4-8ae2-45af-b9ad-d909f5f84aba)

**Comment by dioliviers** [comment]
Aparentemente está tudo ok. 

OBS em prod o bloco de mais lidas está desconfigurado para o modo grid,  ajustado somente em dev falta ajustar em prod

**Comment by caio-ascava** [comment]
Mas pelo mobile ali é necessário aplicar a tradução no WPML, certo? Pelo print que vc enviou.
