### ISSUE TITLE
[AFLUENTES] Criar postagens

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#74]
Criar pelo painel:

- [x] CINE NINJA -> https://novo.midianinja.org/afluente/cine-ninja-em-desenvolvimento/
- [x] XEPA  -> https://novo.midianinja.org/afluente/xepa/
- [x] NINJA FOTO -> https://novo.midianinja.org/afluente/ninja-foto/
- [x] S.O.M -> https://novo.midianinja.org/afluente/s.o.m/
- [x] NEC -> https://novo.midianinja.org/afluente/nec/
- [x] ESTUDANTES NINJA -> https://novo.midianinja.org/afluente/estudantes-ninja/
- [x] ELLA
- [x] FODA
- [x] PODERES
- [x] AMAZONIA
- [x] MINAS
- [x] DESIGN ATIVISTA

Implementar blocos dos afluentes:
- [ ] XEPA
- [ ] NINJA FOTO
- [ ] S.O.M
- [ ] NEC
- [ ] ESTUDANTES NINJA
- [ ] ELLA
- [ ] FODA
- [ ] PODERES
- [ ] AMAZONIA
- [ ] MINAS
- [ ] DESIGN ATIVISTA

**COMEÇAR PELA XEPA**

Utilizar mesmos blocos de vídeo:

- [ ] Bloco de vídeo: utilizar o mesmo que foi implementado na home
- [ ] Slider: implementar um mesmo bloco de slider que será usado na XEPA e no SOM 
SOM:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/c619209b-b152-4172-a41f-fad922f476ea)

XEPA:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/407e49d4-eb11-429c-8423-a5e0c6bb6fd6)

**Comment by daphnemartinsba** [comment]
blocked: aguardando issue #58

**Comment by daphnemartinsba** [comment]
-  inserir o item opinião no menu ancorado
 - Bloco Campanhas: são links externos, sera slider, será montado individualmente
 - Bloco Especiais: serão postagens do CPT Especial com a taxonomia do afluente em questão
 * XEPA:
        - Oportunidade / circuito de formação e ativismo (no cine ninja): não vai ter slider no mobile e vai ser um bloco simples com botão, imagem, título, texto
        - abaixo da paginação inserir o bloco de opinião, publicações com marcador do afluente, exibir últimas colunas -> nossa sugestão é utilizar o bloco de opinião da single de colunista

**Comment by daphnemartinsba** [comment]
- [ ] aplicar bloco homepageposts nos grids

**Comment by julialaurentino** [comment]
- [ ] Padronizar metadado dos posts com o grid da primeira dobra da home
- [ ] Padronizar dimensões das imagens destacadas
- [ ] Ajustar post em destaque de todos os afluentes. Checar qual deve ser listado como destaque em cada caso e aplicar na configuração do bloco
- [ ] Padronizar tamanho dos destaques com o card da direita de maneira responsiva

NINJA Foto:
- [ ] Corrigir logo do card
- [ ] Corrigir diagramação do card
- [ ] Verificar e adicionar redes sociais (facebook e X)
- [ ] Matéria de capa tá repetida com a listagem abaixo, ajustar para o destaque certo

Estudantes NINJA:
- [ ] Ajustar post em destaque conforme o layout
- [ ] Ajustar disposição da segunda dobra, está com a coluna da direita vazia. Verificar se há conteúdo lateral ou se é possível aumentar uma coluna de listagem de post
- [ ] Incluir bloco de Opinião em cima de Quem Somos como no layout

Cine NINJA:
- [ ] Ajustar conteúdo, Estreias da Semana e Cine Ninja Indica estão trazendo a mesma lista

- Estreias da Semana: https://midianinja.org/wp-admin/edit.php?post_type=news&tag=nos-cinemas
- Cine Ninja Indica: https://midianinja.org/wp-admin/edit.php?post_type=news&tag=cine-indica

FODA:
- [ ] Ajustar cor do texto do menu para preto

Poderes Pretos:
- [ ]  Ajustar disposição da segunda dobra, está com a coluna da direita vazia. Verificar se há conteúdo lateral ou se é possível aumentar uma coluna de listagem de post
- [ ] Adicionar bloco de Especiais igual ao da Xepa ativismo: 

- Foto: https://midianinja.org/wp-content/uploads/2023/08/photo_4974752828618812216_y-1.jpg  ou https://midianinja.org/wp-content/uploads/2022/07/img3.png 

- texto: "São quase 20 anos desse momento de encontro e potência de mulheres negras e o Poderes Pretos esteve lá registrando cada momento do Festival Latinidades. "

- botão: Confira a cobertura! (link: [https://midianinja.org/news/latinidade](https://midianinja.org/news/latinidades) )

Minas NINJA:
- [ ] Bloco de galeria buscar galerias de "Festeja Tradição Mineira"

**Comment by daphnemartinsba** [comment]
design ativista:

- [ ] -ao aplicar h5 no texto, a fonte não segue o esperado do style guide
- [ ] bloco de últimos posts (grid) na opiniões, não lista os avatares redondos, e quando a opinião tem imagem de destaque lista a thumb quadrada de imagem
- [ ] para que a paginação exiba o tanto de postagens necessárias para 26 paginações, é necessário aumentar o limite para 364 ao invés de 98

**Comment by caio-ascava** [comment]
Foi identificado que entre os afluentes não possui um padrão do menu alternativo. No entanto, foi avaliado a funcionabilidade das arquives. Caso seja possível e necessário, ajustes finos a serem realizados:

- [ ] Ajuste fino em todas as archives para customização da fonte ninja de "QUEM SOMOS", conforme FIGMA, elas deveriam estar na fonte ninja.

_Os ajustes mapeados abaixo são referentes ao menu alternativo que em alguns casos apresenta-se colado ao bloco superior. Embora não possua um formato padrão deste menu alternativo, os apontamentos inseridos abaixo são necessários._

- **Casa NINJA Amazônia**
Nenhuma alteração, apenas para registrar o formato do menu alternativo.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/1f17a952-c5b1-4d83-b097-371b12786370)
**- Cine Ninja**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/be5e98e1-e6fd-45f8-b19a-9c1d0116eaa1)
**- Design Ativista**
- [ ] Diminuir recuo entre blocos
- [ ] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/31c1aa7d-9004-4b29-8f1f-3093c80a0c9f)
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/12515b0c-ceb2-49ff-9cad-0a35dde4b233)
**- FODA**
- [ ] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/d776442b-3f0c-4298-ba87-d1b97d9a618d)
- NINJA Esporte Clube
Nenhuma alteração, apenas um novo formato de menu alternativo.
- ELLA
- [ ] Aumentar espaçamento entre bloco e menu alternativo
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/109df57d-c325-4550-9494-c1f12cb6938f)
**- Poderes Pretos**
- [ ] Diminuir recuo entre blocos
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/751f8fc7-07c1-4ab1-b8af-037574a5bd3c)

**Comment by caio-ascava** [comment]
Esta issue foi encerrada para abertura da issue X, que tratará as pendencias de adequações, via mobile, das archives de afluentes. [#15](https://github.com/orgs/midianinja/projects/3/views/1?pane=issue&itemId=62902492)
