### ISSUE TITLE
[SINGLE NOTÍCIAS] Corrigir subtítulo e imagem duplicado

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#78]
- Script foi feito no projeto RBA

Referência:
https://gitlab.com/redebrasilatual/rba-site/-/commits/bugfix/duplicated-images

**Comment by rafaelchavesfreitas** [comment]
Estudei o banco de dados e observei que o padrão que precisa ser removido das primeiras linhas do post_content é o seguinte:

```PHP
<div id="audimaWidget"></div>
<script src="https://audio.audima.co/audima-widget.js"></script>
<h3>Subtítulo do post</h3>
[caption id="attachment_${ID}" align="aligncenter" width="1200"]<img class="size-full wp-image-${ID}" src="http://localhost/wp-content/uploads/2023/10/8dejaneiro-gsi.jpg" alt="" width="1200" height="754" /> Foto: Joédson Alves/Agência Brasil[/caption]
```

Implementar no plugin de migração novo comando que pegue todos os posts relevantes (todos os post types de conteúdo?) e no loop aplica o código abaixo em cada post:

```PHP
$content = $post->post_content;
$content = preg_replace('/^<div id="audimaWidget"><\/div>\n/','', $content, limit: 1);
$content = preg_replace('/^<script src="https:\/\/audio.audima.co\/audima-widget.js"><\/script>\n/','', $content, limit: 1);
$content = preg_replace('/^<h3>.*?<\/h3>\n/','', $content, limit: 1);
$content = preg_replace('/^\[caption.*?\]<img.*?\/>.*?\[\/caption\]\n/','', $content, limit: 1);

if($post->post_content != $content) {
    $post->post_content = $content;

    // save post
}
```

**Comment by caio-ascava** [comment]
Foi realizada a avaliação de aproximadamente 150 posts e após correções realizadas pelo Rafa, ficaram ainda 02 posts com divergências. O Rafa fez as alterações e nos testes finais, em dev, ficaram estes. 

Esta havia o sub titulo duplicado:
https://dev.midia.ninja/tecer-palavras-e-sonhos-uma-conversa-com-ana-paula-torquato-membro-da-academia-juiz-forana-de-letras/

Esta havia a imagem duplicada:
https://dev.midia.ninja/mirantes-emocionais-e-o-novo-disco-do-cantor-e-compositor-mineiro-arthur-melo/

**Comment by guimaricardo** [comment]
Titulo e subtitulo ok, faltando corrigir imagens duplicadas;

**Comment by daphnemartinsba** [comment]
- **Encaminhamento Final:** foram reconhecidos alguns padrões que resultaram na duplicação, se ainda assim houverem casos de postagens com elementos duplicados, na reunião semanal, do dia 30 de abril, foi decidido que será resolvida manualmente
