### ISSUE TITLE
[EDITORIAS] Criar ARCHIVE 

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#8]
- [x] Criar Archive para cada editoria (categoria) de post

A lista de editorias está aqui:
https://docs.google.com/spreadsheets/d/1kvVfVBuLmMs9DbJRH2a14d0nGFIOBSKYruEUj-omZzI/edit#gid=990668045

Layout Editoria Política desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=573-2554&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout Editoria Política mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=573-2682&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout Editoria Meio Ambiente desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=572-2107&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout Editoria Meio Ambiente mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=572-2185&t=SBkeDROW6kCINynL-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

**Comment by filipesouzadev** [comment]
Estou retornando a issue pra to do como blocked por conta do bloco últimos posts vertical que precisa de uma implementação para que possamos filtrar as notícias por categoria.
Se o @everaldomatias puder me orientar, posso entrar nisso na segunda.

**Comment by daphnemartinsba** [comment]
- [ ] Aplicar para as demais categorias disponíveis em: https://novo.midianinja.org/category/politica/ estão grifadas
- [ ] Aplicar layout na archive genérica
- [ ] Bloco de destaque: Post listado no bloco de destaque deve ser o post mais recente referente à editoria da archive
    - [x] archive de meio ambiente
    - [ ] demais archives
- [ ] Posts listados no grid deve ser do segundo mais recentes, contando que o primeiro estará em destaque
- [ ] Bloco de destaque: Foto do bloco de destaque deve ser referente ao post mais recente da editoria da archive
- [ ] Bloco de destaque: Retirar sublinhado do título e da editoria da notícia em destaque
- [ ] Bloco de destaque: Editoria do bloco de destaque deve ficar em caixa alta
- [ ] Bloco de destaque: Aumentar altura dos bloco de destaque e aumentar largura da área com blur 
- [ ] Bloco de destaque: Título da notícia fica incompleto mesmo que ainda haja espaço no banner
- [ ] bloco vertical do cabeçalho: Aumentar altura e largura (deve ter o mesmo tamanho do bloco de destaque) do bloco vertical do cabeçalho com slider
- [ ] bloco vertical do cabeçalho: título com fonte ninja não deve quebrar linha
- [ ] bloco vertical do cabeçalho: alterar cor da fonte de título da notícia para #000000
- [ ] bloco vertical do cabeçalho: alterar line height do metadado para 18.85
- [ ] bloco vertical do cabeçalho: segunda notícia fica cortada com o metadado cortado e as vezes o título
- [ ] bloco vertical do cabeçalho: adequar ao figma cor da seta e do fundo da sela do slider, das bolinhas também
- [ ] bloco vertical do cabeçalho: alterar cor da borda do bloco vertical do cabeçalho para a cor da editoria 
- [ ] Centralizar anúncio em referencia aos blocos de destaque e vertical do cabeçalho 
- [ ] bloco vertical do cabeçalho: aplicar cor nos metadados das editorias do bloco vertical do cabeçalho, caso não tenha cor deixar a cor da fonte padrão utilizada no bloco 
- [ ] Alinhar bloco mais lidas com bloco vertical do cabeçalho
- [ ] alinhar coluna esquerda do grid de notícias, ou seja, thumb título e metadado da notícia com a lateral esquerda do bloco de destaque
- [ ] diminuir distância entre bloco mais lidas e thumbs
- [ ] paginação deve ficar mais à esquerda, conforme figma, alinhada à quase metade da thumb da coluna da esquerda do grid
- [ ] retirar sublinhado de títulos, metadado e categorias de mais lidas
- [ ] estilizar metadado de mais lidas para que não quebre a linha
- [ ] inserir anuncio abaixo de mais lidas
- [ ] Grid - Lista de notícias: alterar fonte do metadado de data para 13 px 
- [ ] Grid - Lista de notícias: alterar tamanho da fonte para 24 px (agora está 20 px - 1.25 rem)
- [ ] Traduzir string pelo WPML
- [ ] Paginação: diminuir seta
- [ ] Paginação: Alterar line height do número para 24 px

**Mobile**
- [ ] Iphone max pro 14 e Samsung S23: centralizar blocos
- [ ] Iphone max pro 14 e Samsung S23: aumentar anúncio
- [ ] Iphone max pro 14 e Samsung S23: bloco mais lidas não aparece
- [ ] IIphone max pro 14 e Samsung S23: diminuir espaço entre notícias listadas no grid
- [ ] Iphone max pro 14 e Samsung S23: bloco do cabeçalho slider, padronizar espaço entre título da notícia e metadado, conforme figma

**Comment by daphnemartinsba** [comment]
* Archive de editorias
    - caiu o slide do bloco vertical, mas tem que utilizar newspack, duas notícias
    - vai ter a archive de notícias e vai ter uma archive para cada editoria
        - usar o home.php

**Comment by filipesouzadev** [comment]
Os comentários em aberto estão listados na issue #93

**Comment by caio-ascava** [comment]
- [ ] Avaliar formatação do bloco azul à direita;
- [ ] Avaliar se serão 3 noticias ou duas, ou se ocorre devido a ter apenas 02 relacionadas a alimentação.
- [ ] Achei as letras embaçadas junto ao bloco cinza.
- [ ] Poucas categorias possuem a informação adequada. Sendo que a de cultura foi a melhor avaliada.
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/86418e65-16f2-460f-8303-2a73eea586b1)

Alguns exemplos, não se limitando a:

**Alimentação** https://novo.midianinja.org/category/alimentacao/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/3daa2ca0-e06a-4ac0-a265-c0e9f126797c)

**Agricultura-familiar** https://novo.midianinja.org/category/agricultura-familiar/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/caa1a976-e8c1-459c-9d73-ebc2ce5a0b94)

**Agronegócio** https://novo.midianinja.org/category/agronegocio/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/9122f08d-b8e3-4779-b3dc-6c78d3947df6)

**Agrotóxicos**: https://novo.midianinja.org/category/agrotoxicos/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e1f09e5b-8697-46e4-b6fc-8e641ba5a084)

**Fome**: https://novo.midianinja.org/category/fome/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/832defb2-8cd4-46ea-9fa3-a9e827988f39)
(visualmente, via mobile, única categoria que teve alteração entre IOS e android) - FOME
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/ebd0aa22-9015-4c9b-8cb2-7574a9b0a9f7)

**Inovação** https://novo.midianinja.org/category/inovacao/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/e80a008b-5b34-4f7c-aec8-d2a2601b8d07)

**Maconha medicinal** https://novo.midianinja.org/category/maconha-medicinal/
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/aff8fa7f-cca7-4f9b-a83e-3d37ee884f61)

**IPHONE 14 PRO e S23**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/418800af-8ea2-441d-8f5e-0a6b46daade9)

**Comment by filipesouzadev** [comment]
@caio-ascava boa tarde, tudo bem?
algumas das categorias que você mencionou estarem sem o header, são subcategorias, que pelo menos por hora não tem mesmo.
temos 11 categorias principais que estão na linha 1 deste documento: https://docs.google.com/spreadsheets/d/1kvVfVBuLmMs9DbJRH2a14d0nGFIOBSKYruEUj-omZzI/edit#gid=990668045

no mais, fiz ajustes na versão mobile que commitei e vou subir no staging.

**Comment by daphnemartinsba** [comment]
retornos mobile na issue: #125
