### ISSUE TITLE
[NEWSLETTER] Criar e aplicar bloco da Newsletter no rodapé (footer)

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#81]
Será criado apenas um bloco newsletter para todo site com exceção da HOME e das singles de ESPECIAIS.
- [x] Criar bloco da Newsletter no rodapé (footer).
- [x] Estilizar bloco de acordo com o layout
- [x] Ocultar esse bloco Newsletter do rodapé na HOME e na 404.
- [x] Versões em inglês e em espanhol
- [x] Retirar bloco antigo da newsletter, aplicar novo e enxugar css que está sem função das páginas:
  - Fale conosco
  - FAQ
  - Archive Opiniões
  - Vídeos
 
- [x] Adicionar nas páginas:
  - Seja ninja
  - Single notícias
  - Single opinião 
  - Single Fotografias

**Comment by estercmandrade** [comment]
@filipesouzadev, @thiagolamonte relatou que por algum motivo, ele não lembra exatamente, o Burns desenvolveu o footer meio no código meio no painel... e ai a chamada pro Footer Widget não está no footer.php que é que monta nosso footer.

**Comment by daphnemartinsba** [comment]
- Houve uma alteração no layout da home, portanto:

- [ ] desocultar newsletter pelo widget da home e retirar do bloco ajustando CSS
