### ISSUE TITLE
[FAQ] Alterações nas fontes e no alinhamento

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#82]
- [x] Alterar fonte de pergunte aos ninjas para #333333 
- [x] Alinhar conteúdo ao banner:

staging: ![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/af28e6f5-6871-4ba1-9fa9-75d4f87ca8b5)

Figma:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/88657d75-e6af-4f4a-925d-e9a3e8ee8821)

- [x] Alterar cor de O que é mídia NINJA para #111111
- [x] Internacionalizar strings, text domain: 'ninja'

- [x] Ocultar seta no mobile do iphone
- [x] Revisão fontes após padronização do layout

**Comment by daphnemartinsba** [comment]
@leopiccionia poderia dar apoio ao @thiagolamonte  sobre a questão das setas do mobile?

**Comment by thiagolamonte** [comment]
validação

https://novo.midianinja.org/perguntas-frequentes/
