### ISSUE TITLE
[SEJA NINJA] Ajuste gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#83]
- [x] Alterar fonte de placeholders para manrope, 13 px weight 500 e line height 18.85px
- [x] Ao clicar em cima da seta o dropdown não abre
- [ ] Alterar placeholder "Estado" para "Selecione um estado"
- [ ] Ao selecionar o estado o campo de Cidade deve passar a ter uma seta como a do campo para selecionar o estado
- [ ] Alterar placeholder "Cidade" para "Seleciona uma cidade"
- [x] Internacionalizar strings
- [x] Alterar imagem do banner do desk e mobile
- [x] Arredondar borda dos banners conforme figma
- [x] Alterar weight da fonte A Mídia NINJA para 800 e tamanho para 20 px com line height 26 px

Mobile:
- [x] Aumentar tamanho dos campos
- [x] Alinhar campos com o meio do S do Título "Seja Ninja" e com  "Vem ajudar a reconstruir o Brasil com a gente!"
- [ ] Ajustar seta do mobile:
No iphone:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/9dd66cbf-9d01-4094-962e-7ab4e7a67275)

- [x] Diminuir bloco A Mídia NINJA para que fique do tamanho do botão enviar
- [x] Ajustar a borda de A Mídia NINJA conforme figma
- [x] Alterar o texto "A Mídia Ninja" para "A Mídia NINJA", conforme está no figma
- [x] Ajustar textos para que fiquem com o mesmo alinhamento e quebra de linha do figma

**Comment by daphnemartinsba** [comment]
blocked: decidir comportamento da seta devido às complicações técnicas ou desbloquear as complicações técnicas

**Comment by daphnemartinsba** [comment]
- Alterar placeholder "Estado" para "Selecione um estado" e Alterar placeholder "Cidade" para "Seleciona uma cidade"
  - Manterá como Estado e Cidade para que após a seleção dos estado, a label do placeholder da cidade permaneça a mesma
- Ao selecionar o estado o campo de Cidade deve passar a ter uma seta como a do campo para selecionar o estado e  Ajustar seta do mobile:
  - Foi aderida a seta padrão do campo

**Comment by daphnemartinsba** [comment]
- [ ] Alterar fonte de placeholders para manrope, 13 px weight 500 e line height 18.85px
- [ ] Arredondar as bordas do banner conforme figma

- [ ] Alterar background para #f5f5f5

- [ ] Mobile Iphone pro max 14: campos de Seleção estão com tamanho e cor diferente

**Comment by caio-ascava** [comment]
- [ ] Para mobile, Iphone 14 Pro, os campos de seleção continuam com tamanhos diferentes e também há um espaçamento diferente nestes dois campos (estado e cidade).

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/c65e6d5a-db61-415e-bbc7-39b58bc2a509)

- [ ]  O Bloco preto A mídia NINJA precisa ser inserida a linha abaixo deste título.
- [ ] Aproximar os ícones das redes sociais

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/d9f2d24f-c1fc-40e8-b07a-d4bcd99db79a)

**Comment by daphnemartinsba** [comment]
- [ ] Alterar foto do mobile

**Comment by daphnemartinsba** [comment]
retorno na issue #127
