### ISSUE TITLE
[CABEÇALHO/RODAPÉ] Inserção e re-ordenação de seletores de idiomas e redes sociais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#85]
- [x] Cabeçalho: Inserir seletor de idiomas:
https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1760%3A4208&mode=design&t=2Brap0s6CByceKwF-1

- [x] menu do hamburguer: inserir seja ninja em seções
- [x] menu do hamburguer: inserir Fale Conosco abaixo de loja
- [x] Investiga/ajustar transição do cabeçalho para o menu reduzido

- [x] ordem das redes sociais: Instagram - Youtube - X - Facebook - TikTok - Telegram - Flickr

**Comment by everaldomatias** [comment]
As correções que apliquei até o momento foram:

- Passagem do menu para o menu reduzido: se rolar a barra de rolagem com o clique do mouse, o menu não se torna reduzido
- dropdown de notícias fica voando sozinho quando abre ele e rola a página pra baixo:
- Alteração solicitada pelo cliente: Tornar os ícones do Menu principal para que os submenus apareçam quando passar o mouse por cima, não clicando, como está atualmente (ativar hover)

**Comment by daphnemartinsba** [comment]
- [ ] conteúdo das páginas, archives e post estão indo para atrás do header

**Comment by daphnemartinsba** [comment]
retorno na issue #126
