### ISSUE TITLE
[ESPECIAIS] Criar blocos e postagens

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#86]
- [x] COP 27
- [x] NINJAnaavenida
- [x] copa femiNINJA

**Comment by daphnemartinsba** [comment]
- Foi criado o bloco de opinião

**Comment by daphnemartinsba** [comment]
O Especial de Paris deve ser validado com base nas orientações desse doc:
https://docs.google.com/document/d/10uy9jPoMczxYueg_ar1fW-2Btnsw-QKWswqU6RtHsL8/edit

Os demais Especiais que não estão no figma foram feitos com base no site em produção [midianinja.org](https://midianinja.org/)
os links se encontram nessa planilha:
https://docs.google.com/spreadsheets/d/1kvVfVBuLmMs9DbJRH2a14d0nGFIOBSKYruEUj-omZzI/edit#gid=994743894

**Comment by caio-ascava** [comment]
**Validação Desktop:**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/efde339c-8ce9-486c-8c9b-30e768b7264f)

- [ ] Bloco "ULTIMAS" no figma a borda é preta
- [ ] Bloco "ULTIMAS"no figma, tem apenas 02 noticias e possui as setas para seguir para outras.
- [ ] Bloco "ULTIMAS"no figma, as noticias estão com informação de quanto tempo foi a publicação e onde.
- [ ] Bloco de "NOTÌCIAS" no figma não tem este título, apenas as thumbs, sendo a primeira apenas com imagem.
- [ ] Neste bloco de noticias, no figma não há a opção de visualizar mais (setas abaixo das noticias)
- [ ] Thumb do bloco de noticias deve possuir a tarja com a categoria e sua cor respectiva. 
- [ ] No figma não há o bloco de Galeria (imagens)
- [ ] No bloco "COP27 / 2022 esta tarja preta é menor (durante a validação identifiquei a tarja aparece em desktop como deveria ser para mobile, e vice-versa.
- [ ] Ajuste da fonte "SOBRE"
- [ ] Bloco preto "Videos" não foi identificado no layout.

**Validação Mobile:**
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/37d47853-63a2-4a92-92e5-5a8415fc0b65)

- [ ] Bloco "ÚLTIMAS" tem a borda preta do bloco
- [ ] Bloco "ÚLTIMAS" , após a noticia no FIgma, tem há qto tempo foi a publicação e onde
- [ ] Bloco "ÚLTIMAS" , após as 03 noticias tem a seta e pontinhos indicando haver outras ultimas noticias.
- [ ] No figma, as noticias em thumbs não possuem o título "NOTÌCIAS"
- [ ] No figma, após as Thumbs e noticias, há um botão de "ler mais noticias", porem em prod são as setas e pontinhos.
- [ ] No iphone foi identificado que os termos "noticias", "sobre" e "galeria" estão com as fontes estilizadas conforme Design Tokens, no entanto só deveria estar aplicado ao termo "OPINIÂO".
- [ ] A tarja preta, escrita COP27 / 2022 no Figma é como se fosse um grifado, mas em produção se estende até o final da tela.
- [ ] No iphone, as Embeds de Instagram não estão carregando.

**Comment by caio-ascava** [comment]
Após call realizado (Caio, Daphne e Ester), definimos que: 
- O bloco 'ÚLTIMAS" permanecerá conforme padrão do site com a borda cinza claro.
- Foi inserida a data da postagem e por quem neste bloco;
- Antes das thumbs de noticias, o termo "notícia" permanecerá como titulo desta seção.
- Foi ajustado a tarja preta, grifado, de COP27 / 2022
- Não haverá a paginação do bloco últimas, indicando outras noticias no bloco de "ultimas" pois as demais noticias estão direcionadas no bloco "NOTÍCIAS"

**Comment by daphnemartinsba** [comment]
Os ajustes listados acima serão considerados mapeamentos de  ajustes finos
