### ISSUE TITLE
[DESIGN TOKENS] Ajustes gerais e aplicação de fontes de h5 e h6

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#88]
Styleguide: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-3&mode=design&t=I2vlWLtDC59ec7za-0
Componentes: https://www.figma.com/file/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=1-2&mode=design&t=I2vlWLtDC59ec7za-0

* As especificações das fontes confore styleguide devem fazer para os CPTs, posts e páginas

- [x] Alterar cor da fonte h1, h2, h3, h4 para #111111, no momento está #262626 
- [x] alterar h2 para: 
font-size: 32px;
font-weight: 800;
line-height: 38.4px;
letter-spacing: -0.02em;
text-align: left;

na single de posts no staging:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/730d2997-17be-44a6-9f16-221a8545ac00)

- [x] alterar h3 para:
font-size: 24px;
font-weight: 800;
line-height: 30px;
letter-spacing: -0.01em;
text-align: left;

na single de posts no staging:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/45a9502a-bdb8-4250-9fa6-16ed10295b6e)

- [x] alterar h4 para:

font-size: 20px;
font-weight: 700;
line-height: 26px;
text-align: left;

na single de posts do staging:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/d2ec88e4-72ab-4fb5-a4e6-78f4c8f141d5)

- [x] Alterar parágrafo para:
font-size: 16px;
font-weight: 500;
line-height: 22.4px;
text-align: left;

- [ ] Aplicar fontes h5 e h6

**Comment by caio-ascava** [comment]
- [ ] Aplicar fontes h5 
<h5> Manrope Medium 13 </h5>
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/faa20d05-bf9a-4890-acb1-34e5ff0a0a81)

- [ ] Aplicar fontes h6 
<h6> Manrope Medium 10 </h6>
![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/b9e0b2e1-0f2e-4e1e-bfbb-9250329a4cdb)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/9c033751-afc8-41e9-a6c7-7fe099ae0d51)

**Comment by daphnemartinsba** [comment]
- [ ] aplicar h3 (exemplo: single de fotografias)

**Comment by daphnemartinsba** [comment]
retorno #160
