### ISSUE TITLE
[ANUNCIOS] Configurar plugin Newspack com Google Ads

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#89]
https://novo.midianinja.org/wp-admin/admin.php?page=newspack-advertising-wizard#/

- [x] Configurar plugin Newspack com Google Ads

**Comment by marinarcruz** [comment]
03/06: fizemos configuração dos anúncios e entregamos em 31/05.
@estercmandrade analisando posicionamento dos ads o site para aplicação direta conforme layout.

**Comment by marinarcruz** [comment]
12/06: Reunimos com Gian hoje e configuramos os anúncios do Google para aparecerem nas singles e archives. Os anúncios pelo newspack ficarão somente na home. Pretendemos com isso melhorar a monetização do site. Gian ficou de acompanhar os impactos dessa mudança e validar. Marina retomar contato semana que vem para verificar se melhorou.
