### ISSUE TITLE
[SOBRE NÓS] 

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#9]
- [x] Criar página  e estrutura dos blocos
- [ ] Aplicar layout

https://novo.midianinja.org/a-midia-ninja/

**Comment by daphnemartinsba** [comment]
blocked: aguardando aprovação do layout

**Comment by marinarcruz** [comment]
@estercmandrade falta estilizar o botão - confirmando com cliente
