### ISSUE TITLE
[ARCHIVE NOTÍCIAS] Criar ARCHIVE GENÉRICA

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#92]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=2961-5712&t=ysXpqsxHT2QogI9R-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=3485-4932&t=ysXpqsxHT2QogI9R-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- [x] Archive de TODAS as Notícias
- [ ] Archive de taxonomias

-  **usar o home.php**

**Comment by caio-ascava** [comment]
- [ ] Aplicar cabeçalho na archive genérica
( ttps://novo.midianinja.org/category/fome/ )

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/d9c8badc-06a5-4e5b-8e31-060565eb4b6e)

**Comment by filipesouzadev** [comment]
Fala @caio-ascava beleza?
Acho que as validações que você fez aqui são referentes a archive de editorias.
Essa archive genérica fica no novo https://novo.midianinja.org/noticias

**Comment by caio-ascava** [comment]
- [ ] 1. Alinhar blocos (reparar que a segunda thumb tem sua borda inicial no fim da borda do bloco cinza e borda final com mesmo espaçamento do bloco acima citado)
- [ ] 2. Este bloco acima em cinza, no figma, apresenta-se um pouco maior.
- [ ] 3. No bloco mais lidas, no figma, as noticias possuem um espaçamento menor, sendo apresentadas 4 series. 
- [ ] 4. As setas e pontilhados precisar ser ajustadas quanto as cores.
- [ ] 5. Falta incluir as datas abaixo dos títulos
- [ ] 6. A partir da página 2, as imagens e títulos sofrem impactos de sobreposição.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/600e3a95-5f84-4aa7-aff9-9710cbfb2df9)

**Comment by filipesouzadev** [comment]
@caio-ascava sobre o item:
2. O bloco de "mais lidas", no figma se apresenta após o bloco de "ultimas", porem em staging ele está no final da tela

ficou definido que seguiremos a ordem de empilhamento do HTML pois modificar o local desse elemento é uma tarefa de certa complexidade e exigiria um tempo maior.

**Comment by daphnemartinsba** [comment]
- [ ] Os títulos dentro do box de mais lidas estão todos em caixa alta

**Comment by daphnemartinsba** [comment]
retornos na #120
