### ISSUE TITLE
Bloco Últimos posts (Horizontal)

### ISSUE THREAD

**Issue by estercmandrade** [midianinja/ninja-wp-theme#94]
Modelo de vídeos:

- [x] Além de configurar via ID da playlist, adicionar opção para configurar ID do canal

Modelos de especiais:

- [x] adicionar campo para inserir hiperlink no título do bloco

- [x] adicionar uma opção para listar ou não subpáginas (hierarquia)

**Comment by daphnemartinsba** [comment]
"adicionar uma opção para listar ou não subpáginas (hierarquia)": resolvida na issue [#98](https://github.com/midianinja/ninja-wp-theme/issues/98)

**Comment by everaldomatias** [comment]
@daphnemartinsba já está disponível para validação os itens:
- Além de configurar via ID da playlist, adicionar opção para configurar ID do canal
- adicionar campo para inserir hiperlink no título do bloco

**Comment by daphnemartinsba** [comment]
- [ ] retirar sublinhado dos títulos de vídeos e especiais

**Comment by daphnemartinsba** [comment]
Bloco de vídeo com ID do canal e opção de hierarquia:

https://github.com/midianinja/ninja-wp-theme/assets/75261677/9a22ae17-8446-4044-a38f-29e50bcdf05c
