### ISSUE TITLE
[TV NINJA] Alterações de layout

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#95]
- solicitar id do canal do youtube para ninjas: UCwefw3viiiaxprsV6jgJvEA

- [x] alterar bloco mais vídeos
layout:

![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/94a3d20d-960a-4596-8051-6b46e3b73bf6)

- [x] retirar bloco de grid antes de shorts
- [x]  trocar cor de fundo de shorts para branco (a mesma cor utilizada no resto da página)

**Comment by daphnemartinsba** [comment]
blocked: desenhar e tarefar as alterações do layout solicitadas

**Comment by marinarcruz** [comment]
- [ ] debugar o motivo pelo qual o bloco principal da esquerda não fica com o CSS aplicado quando o bloco de shorts é exibido
- [ ] resolver o bug e aplicar a solução conforme layout.

**Comment by thiagolamonte** [comment]
https://dev.midia.ninja/tv-ninja/

**Comment by thiagolamonte** [comment]
validação em DEV

https://dev.midia.ninja/tv-ninja/

comentário: 
O layout prevê que o video de destaque não tenha icone dos ninjas e titulo do vídeo no cabeçalho do player. É previsto também que o botão de Play vermelho seja redondo e cinza. Todos esses elementos estão dentro de um iframe o que não permite que eles sejam retirados ou estilizados

**Comment by daphnemartinsba** [comment]
retornos sobre shorts na issue #148
