### ISSUE TITLE
[SINGLE OPINIÃO] Ajustes gerais e alteração do layout nas redes sociais

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#97]
Layout desktop: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=862-3712&t=B6KwTltqpMjWTeMR-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525
Layout mobile: https://www.figma.com/proto/ZVvIybXICJvCLB7sVbEWY5/M%C3%ADdia-NINJA-UI-V2?type=design&node-id=862-4068&t=B6KwTltqpMjWTeMR-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A10525

- [x] Conteúdo do texto quando contém tabela extrapola limite previsto no layout
    - Exemplo com tabela: https://novo.midianinja.org/opiniao/os-desafios-de-2024-para-os-designers-ativistas/
        - tabela está quebrada
- [x] Alinhar bloco de vídeos ao conteúdo de texto 
https://novo.midianinja.org/opiniao/priscilla-a-mulher-do-rei/
- [x] alterar cor e fonte do metadado de data
- [x] padronizar espaço ocupado pelo resumo:   
    - exemplo correto: https://novo.midianinja.org/opiniao/as-redes-sociais-e-sua-responsabilidade-na-violencia-extrema/
    - exemplo que precisa de ajuste: https://novo.midianinja.org/opiniao/os-desafios-de-2024-para-os-designers-ativistas/
- [x] conheça os colunistas não condiz com o layout, estilizar conforme figma

Alterações solicitadas pelo cliente:
- [x] inserir mais redes sociais e alterar ordem do bloco de co authors:  Instagram - X - Facebook - Youtube - Tik Tok
- [ ] inserir mais redes sociais e alterar ordem no fim do post: Instagram - X - Facebook - Youtube - Tik Tok

**Comment by daphnemartinsba** [comment]
- Funcionamento do card de colunista: deve aparecer somente quando o post for de um autor que tiver a marcação de que é um colunista
Local onde marca se é colunista:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/54d5f999-ebb6-44e0-a2be-590cee852bd1)


- No cenário em que o autor do post não está com o campo de que é colunista marcado, deve aparecer o mesmo componente utilizado na single, "por: autor"
Imagem do componente:


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/879cac45-94aa-4e4c-8586-0086aa56a7de)

**Comment by caio-ascava** [comment]
- [ ] Padronizar tamanho dos ícones de redes sociais.
- [ ] Sumiu o bloco escuro a direita, com a foto do perfil, descrição e ícones de redes sociais
- [ ] Não está aparecendo mais a data da noticia, apenas a data da opinião.

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/24a82211-2d80-41b7-87fd-9865c2392dae)

![Image](https://github.com/midianinja/ninja-wp-theme/assets/151761173/3e718060-6876-436e-ae48-df1b6bbb4315)

**Comment by daphnemartinsba** [comment]
será resolvida na #137
