### ISSUE TITLE
[HOME] Ajustes no layout e bloco Colunistas

### ISSUE THREAD

**Issue by daphnemartinsba** [midianinja/ninja-wp-theme#99]
- [x] Alinhar e centralizar lista de notícias com o bloco da notícia em destaque, as três notícias não devem chegar no limite do bloco
- [x] Na lista de notícias, do grid, logo abaixo da notícia em destaque, os metadados das editorias deve ter a cor que foi aplicada na categoria
- [x] No bloco útilmas o metadado das editorias deve manter a fonte conforme o figma, a cor da fonte deve ser a cor do fundo selecionada na editoria
- [x] Diminuir distância da lista em grid e do bloco de últimas das notícias em destaque, tomar cuidado para manter o grid alinhado com últimas
- [x] Sombra do slider de especiais deve ficar à direita, não à esquerda
- [x] Diminuir tamanho do bloco mais lidas, no figma (proto) está com  473 px (resolução 1920), no staging está com 518
- [x] Bloco mais lidas: aumentar distância entre notícia e slider
- [x] Bloco colunas: diminuir arredondamento da borda
- [x] Bloco colunas: avatar utilizado não condiz com o avatar do autor (verificar como o bloco conheça os colunistas foi feito). Em algumas postagens de um avatar específico o título fica com espaço maior em relação ao avatar
- [x] Bloco colunas: manter duas opiniões por slide, título deve alinhar à esquerda, manter tamanho do bloco ao trocar de slide, diminuir distância de bloco de citação
- [x] alinhar bloco casa amazônia com fim da lista do grid
- [ ] bloco de vídeo: ao utilizar o slide deve have ra mesma sombra na thumb do vídeo à esquerda. quando cehgar no último slide , à direita não deve masi ter sombra
- [ ] bloco de acervo: slider deve ficar mais para baixo, meio no limite da thumb, sombra deve ter o mesmo funcionamento do bloco de vídeo

- [x] Blur da notícia em destaque fica cortado

Issue será atualizada referente ao mobile (**não considerar issue bloqueada**)

**Comment by barbaburns** [comment]
item: alinhar bloco casa amazônia com fim da lista do grid; 

só é possivel alinhar esse bloco se o conteudo do bloco colunas tiver titulos curtos, igual ao figma. caso contrario o bloco colunas cresce em altura e empura o bloco amaziona para baixo.

**Comment by daphnemartinsba** [comment]
- [ ] alterar fonte do metadado das datas - > aplicar h5

**Comment by barbaburns** [comment]
sombra dos slider precisa ser desenvolvido via js.

**Comment by daphnemartinsba** [comment]
- [ ]  revisão dos tamanhos dos titulos dos blocos na home

**Comment by daphnemartinsba** [comment]
- [ ] Mobile: metadado de bloco últimas esta no lugar de string EM
- [ ] Mobile: setas do slide estão trocadas


![Image](https://github.com/midianinja/ninja-wp-theme/assets/75261677/4f528a3b-f1eb-4a54-8633-0253d63c4b7c)


- [ ] Blocos não exibem metadado especiais * (confirmar se precisa ser feito)
- [ ] Mobile: slide de mais lidas está sobrepondo o texto
- [ ] Mobile: listar mais duas notícia no grid abaixo de mais lidas 
- [ ] Mobile: diminuir espaço entre balão e bloco de colunas
- [ ] Mobile: diminuir bloco de colunas para duas postagens
- [ ] Mobile: bloco todos os colunistas está sem slide, lista muitos
- [ ] Bloco acervo está pixel perfect e não tem slide
